table _Measures
	lineageTag: ab04c4a4-5f0c-4a86-a69c-14d142e6eb1e

	measure 'Total Revenue' =
			
			SUM ( Fact[Sales Amount] )
		lineageTag: e81d7dbf-c154-44b5-8bf0-d0e930a86253

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2024' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2024 )
			
			```
		lineageTag: 29172e91-ab0f-41ab-8a72-23f61df6203c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2023' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2023 )
			
			```
		lineageTag: d0e3180e-8c4c-4661-b85e-9a26ef1b7c03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2022' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2022 )
			
			```
		lineageTag: 037b69ab-9510-483a-96d8-1fff85ccabe3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YoY %' =
			
			DIVIDE ( [Total Revenue 2024] - [Total Revenue 2023], [Total Revenue 2023], 0 )
		lineageTag: 1c98e2df-69b8-48f9-be5a-134f4679bce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Target' =
			
			SUMX ( Dim_Target, VALUE ( Dim_Target[Sales_Target] ) )
		lineageTag: 7bf1e802-6ab8-4359-8bdb-290fddc89c69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achievement %' =
			
			VAR TargetYear = VALUE ( SELECTEDVALUE ( Dim_Target[Year], "2024" ) )
			VAR RevenueSamePeriod =
			    CALCULATE ( [Total Revenue], Dim_Date[year] = TargetYear )
			RETURN
			    DIVIDE ( RevenueSamePeriod, [Total Target], 0 )
		lineageTag: 1bb2c99b-89f1-46c8-aa2d-c259b70765fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Variance (AED)' =
			
			VAR TargetYear = VALUE ( SELECTEDVALUE ( Dim_Target[Year], "2024" ) )
			VAR RevenueSamePeriod =
			    CALCULATE ( [Total Revenue], Dim_Date[year] = TargetYear )
			RETURN
			    RevenueSamePeriod - [Total Target]
		lineageTag: ca93b706-5534-44d3-95fb-08ddb62f476b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achievement Status' = ```
			
			SWITCH (
			    TRUE (),
			    [Achievement %] >= 1,    "On Target",
			    [Achievement %] >= 0.9,  "Near Target",
			    "Below Target"
			)
			
			```
		lineageTag: 517db952-1946-49f7-a4af-3e0dd0fd72c2

	measure 'Active Outlets' =
			
			DISTINCTCOUNT ( Fact[outlet_id] )
		formatString: 0
		lineageTag: d90bd69a-d483-41e7-a6d4-5cab463bbfbb

	measure 'Outlet Universe' = ```
			
			COUNTROWS ( Dim_outlet )
			
			```
		formatString: 0
		lineageTag: ec828cb2-df37-445b-bab2-3603c478a8d4

	measure 'Outlet Coverage %' = ```
			
			DIVIDE ( [Active Outlets], [Outlet Universe], 0 )
			
			```
		lineageTag: 1d03f3c1-6ad3-4a8c-a603-c42513f4ea4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Revenue per Outlet' = ```
			
			DIVIDE ( [Total Revenue], [Active Outlets], 0 )
			
			```
		lineageTag: 82d2dc7c-157d-46c8-9cc9-c1ed27946ffb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Revenue per Outlet 2024' =
			
			DIVIDE ( [Total Revenue 2024], [Active Outlets], 0 )
		lineageTag: 3d1dcdfd-f67f-40d5-9f66-5b6196d29a53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distributor Rank' =
			
			RANKX ( ALLSELECTED ( Fact[distributor_name] ), [Total Revenue], , DESC, Dense )
		formatString: 0
		lineageTag: 06d753d7-1d88-4068-bc69-0dd58552279b

	measure 'Top Distributor' =
			
			VAR T = TOPN ( 1, ALLSELECTED ( Fact[distributor_name] ), [Total Revenue], DESC )
			RETURN
			    MAXX ( T, Fact[distributor_name] )
		lineageTag: 7ceec4d3-e3e2-4db6-8346-699df4b2060f

	measure 'Distribution Index' = ```
			
			[Outlet Coverage %] * 100
			
			```
		lineageTag: 36045b38-37fd-4e15-99ea-5ea10d49c024

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promo Compliance Index' = ```
			
			AVERAGE ( Fact[promotion_flag] ) * 100
			
			```
		lineageTag: d7753f76-26ae-474b-8d05-1f28a38b18b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Achievement Index' = ```
			
			MIN ( [Achievement %] * 100, 100 )
			
			```
		lineageTag: 3fe6a955-d4a2-4347-ba90-838d085f3e69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CD Health Score' = ```
			
			( [Distribution Index] + [Promo Compliance Index] + [Sales Achievement Index] ) / 3
			
			```
		lineageTag: 780a9b04-21e2-4960-87b6-d6db358034ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Health Score Status' =
			
			SWITCH (
			    TRUE (),
			    [CD Health Score] >= 80, "Strong",
			    [CD Health Score] >= 60, "Moderate",
			    "Needs Attention"
			)
		lineageTag: 24c551e7-a342-4a1b-a44a-757083687515

	measure 'Revenue (Current Year)' = [Total Revenue 2024]
		lineageTag: 9df5c348-9a42-46bf-83e0-f25cef8b0d42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue (Prior Year)' = [Total Revenue 2023]
		lineageTag: 65e91817-7d4d-41b5-aad0-3df4d0573296

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI HTML - Achievement' =
			
			VAR _Status   = [Achievement Status]
			VAR _AchPct   = [Achievement %]
			VAR _Color    = SWITCH ( TRUE (), _AchPct >= 1, "#2C5C3C", _AchPct >= 0.9, "#8C5C0D", "#8C2E20" )
			VAR _Bg       = SWITCH ( TRUE (), _AchPct >= 1, "#E7F2EB", _AchPct >= 0.9, "#FAF1DF", "#F8E8E4" )
			VAR _Accent   = SWITCH ( TRUE (), _AchPct >= 1, "#3F7D52", _AchPct >= 0.9, "#BE7A12", "#B23E2B" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid " & _Accent & ";
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>ACHIEVEMENT</div>" &
			"<div style='font-size:28px;font-weight:700;color:" & _Color & ";line-height:1;'>" & FORMAT ( _AchPct, "0.0%" ) & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>vs 100% target</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Status & "</div>" &
			"</div>"
		lineageTag: 9f26d9ea-f3c6-47ff-a38e-bcd1d759acbe

	measure 'KPI HTML - Avg Delivery Days' =
			
			VAR _Avg = [Avg Delivery Days]
			VAR _Target = 2
			VAR _Diff = _Avg - _Target
			
			VAR _Color =
			    IF ( _Diff >= 0, "#C27C00", "#2C5C3C" )
			
			VAR _Bg =
			    IF ( _Diff >= 0, "#F7E8B5", "#E7F2EB" )
			
			VAR _Sign =
			    IF ( _Diff >= 0, "+", "-" )
			
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			background:#FFFFFF;
			border-top:3px solid #2F5F8F;
			border-radius:10px;
			padding:16px 18px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='font-size:10px;
			font-weight:700;
			letter-spacing:1px;
			color:#67726C;
			text-transform:uppercase;
			margin-bottom:8px;'>
			AVG DELIVERY DAYS
			</div>
			
			<div style='font-size:28px;
			font-weight:700;
			color:#1C2624;
			line-height:1;'>" &
			FORMAT ( _Avg, "0.0" ) &
			" <span style='font-size:18px;font-weight:600;'>days</span>
			</div>
			
			<div style='font-size:11px;
			color:#67726C;
			margin:8px 0 10px;'>
			territory average, all regions
			</div>
			
			<div style='display:inline-block;
			font-size:11px;
			font-weight:600;
			padding:3px 9px;
			border-radius:6px;
			background:" & _Bg & ";
			color:" & _Color & ";'>" &
			_Sign &
			FORMAT ( ABS ( _Diff ), "0.0" ) &
			"D VS TARGET " &
			FORMAT ( _Target, "0.0" ) &
			"D
			</div>
			
			</div>"
		lineageTag: 4e19ff48-ebf5-423a-82e5-79a131780c62

	measure 'KPI HTML - Outlet Coverage' =
			
			VAR _Coverage = [Outlet Coverage %]
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #0D5C56;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>OUTLET COVERAGE</div>" &
			"<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>" &
			[Active Outlets] & "<span style='font-size:14px;font-weight:500;color:#67726C;'> / " & [Outlet Universe] & "</span></div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>active outlets of universe</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:#E2EFEE;color:#0D5C56;'>" & FORMAT ( _Coverage, "0.0%" ) & " covered</div>" &
			"</div>"
		lineageTag: fae89983-1af8-4e90-8d2f-100eb2554b99

	measure 'KPI HTML - Revenue' = ```
			
			VAR _Status      = [Achievement Status]
			VAR _AchPct      = [Achievement %]
			VAR _Color       = SWITCH ( TRUE (), _AchPct >= 1, "#2C5C3C", _AchPct >= 0.9, "#8C5C0D", "#8C2E20" )
			VAR _Bg          = SWITCH ( TRUE (), _AchPct >= 1, "#E7F2EB", _AchPct >= 0.9, "#FAF1DF", "#F8E8E4" )
			VAR _ValueText   = "AED " & FORMAT ( [Total Revenue 2024], "#,##0,,.0" ) & "M"
			VAR _TargetText  = "Target AED " & FORMAT ( [Total Target], "#,##0,,.0" ) & "M"
			VAR _VarSign     = IF ( [Revenue Variance (AED)] >= 0, "+", "-" )
			VAR _VarText     = _VarSign & "AED " & FORMAT ( ABS ( [Revenue Variance (AED)] ), "#,##0,,.0" ) & "M"
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #0D5C56;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>TOTAL REVENUE 2024</div>" &
			"<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>" & _ValueText & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>" & _TargetText & "</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _VarText & "</div>" &
			"</div>"
			
			```
		lineageTag: 2d50162a-e20c-4658-ae0d-edf6530703c7

	measure 'KPI HTML - CD Health Score' = ```
			
			VAR Score    = ROUND([CD Health Score], 0)
			VAR DistVal  = ROUND([Distribution Index], 0)
			VAR PromoVal = ROUND([Promo Compliance Index], 0)
			VAR SalesVal = ROUND([Sales Achievement Index], 0)
			
			-- Donut math (radius = 40, circumference = 2π×40 ≈ 251.2)
			VAR Circ    = 251.2
			VAR Filled  = DIVIDE(Score, 100) * Circ
			VAR Gap     = Circ - Filled
			
			-- Bar widths (max bar = 180px)
			VAR DistW   = DIVIDE(DistVal,  100) * 180
			VAR PromoW  = DIVIDE(PromoVal, 100) * 180
			VAR SalesW  = DIVIDE(SalesVal, 100) * 180
			
			RETURN
			
			"<div style='display:flex;align-items:center;gap:20px;padding:20px;box-sizing:border-box;background:#FFFFFF;
			             font-family:""Segoe UI"",sans-serif'>" 
			&
			
			  -- DONUT SVG
			  "<svg width='110' height='110' viewBox='0 0 110 110'>" &
			    "<circle cx='55' cy='55' r='40' fill='none'
			             stroke='#E8E4DC' stroke-width='10'/>" &
			    "<circle cx='55' cy='55' r='40' fill='none'
			             stroke='#C8972B' stroke-width='10'
			             stroke-dasharray='" & Filled & " " & Gap & "'
			             stroke-linecap='round'
			             transform='rotate(-90 55 55)'/>" &
			    "<text x='55' y='50' text-anchor='middle'
			           font-size='17' font-weight='700' fill='#C8972B'>" & Score & "</text>" &
			    "<text x='55' y='65' text-anchor='middle'
			           font-size='10' fill='#999'>/ 100</text>" &
			  "</svg>" &
			
			  -- BARS
			  "<div style='flex:1'>" &
			
			    -- Distribution
			    "<div style='margin-bottom:10px'>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size='12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Distribution</span>" &
			        "<span style='font-weight:600;color:#222'>" & DistVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#1A5C5A;width:" & DistW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			    -- Promo Compliance
			    "<div style='margin-bottom:10px'>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size:12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Promo Compliance</span>" &
			        "<span style='font-weight:600;color:#222'>" & PromoVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#C8972B;width:" & PromoW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			    -- Sales Achievement
			    "<div>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size:12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Sales Achievement</span>" &
			        "<span style='font-weight:600;color:#222'>" & SalesVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#8B1A1A;width:" & SalesW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			  "</div>" &
			"</div>"
			```
		lineageTag: d08f19cf-19cb-4c67-b168-d986f0403b71

	measure 'KPI HTML - Territory Achievement' = ```
			
			VAR _Pct    = [Achievement %]   
			VAR _Txt    = FORMAT(_Pct * 100, "0.0") & "%"
			VAR _Arc    = IF(_Pct >= 1, "#1A5C5A", "#C0392B")
			VAR _Status = IF(_Pct >= 1, "On Target", "Below Target")
			VAR _PillBg = IF(_Pct >= 1, "#E3EEE0", "#FCEAEA")
			VAR _PillFg = IF(_Pct >= 1, "#1A5C5A", "#8B1A1A")
			
			-- 180° gauge  |  r=75  |  half-circumference = 235.6
			-- 0% = left (9 o'clock)   120% = right (3 o'clock)
			VAR _H    = 240
			VAR _Fill = DIVIDE(MIN(_Pct, 1.2), 1.2) * _H
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>"
			 &
			"<p style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222;margin:0 0 2px'>TERRITORY ACHIEVEMENT</p>" &
			"<div style='text-align:center'>" &
			"<svg width='220' height='132' viewBox='0 0 220 132'>" &
			
			  -- Gray background track (full 180°)
			  "<circle cx='110' cy='115' r='75' fill='none' stroke='#E8E4DC' stroke-width='14'" &
			  " stroke-dasharray='" & _H & " " & _H & "' transform='rotate(180 110 115)'/>" &
			
			  -- Colored fill arc
			  "<circle cx='110' cy='115' r='75' fill='none' stroke='" & _Arc & "' stroke-width='14'" &
			  " stroke-dasharray='" & _Fill & " 999' stroke-linecap='round'" &
			  " transform='rotate(180 110 115)'/>" &
			
			  -- White tick at 100% position (30° from right = upper-right of arc)
			  "<line x1='169' y1='81' x2='181' y2='74' stroke='white' stroke-width='2.5'/>" &
			
			  -- Percentage value
			  "<text x='110' y='92' text-anchor='middle' font-size='26' font-weight='700'" &
			  " fill='" & _Arc & "'>" & _Txt & "</text>" &
			
			  -- Status pill
			  "<rect x='57' y='97' width='106' height='18' rx='9' fill='" & _PillBg & "'/>" &
			  "<text x='110' y='110' text-anchor='middle' font-size='9'" &
			  " fill='" & _PillFg & "' font-weight='600'>● " & _Status & "</text>" &
			
			  -- Axis labels: 0% left · 100% upper-right · 120% right
			  "<text x='18'  y='124' text-anchor='middle' font-size='8.5' fill='#bbb'>0%</text>"  &
			  "<text x='183' y='62'  text-anchor='middle' font-size='8.5' fill='#bbb'>100%</text>" &
			  "<text x='202' y='124' text-anchor='middle' font-size='8.5' fill='#bbb'>120%</text>" &
			
			"</svg></div>" &
			"<p style='font-size:10px;color:#aaa;text-align:center;margin:0'>" &
			"of 2024 revenue target — AED 10.6M</p>" &
			"</div>"
			```
		lineageTag: 991594ac-5962-4007-8f0d-2f7ca049fed6

	measure 'KPI HTML - Distributor Performance' = ```
			
			
			-- ① Base data
			VAR _All =
			    ADDCOLUMNS(
			        VALUES('Fact'[distributor_name]),         
			        "@Rev", [Revenue (Current Year)]
			    )
			
			VAR _MaxRev   = MAXX(_All, [@Rev])
			VAR _MaxBarPx = 200
			
			-- ② Top 5
			VAR _Top5 = TOPN(5, _All, [@Rev], DESC)
			
			VAR _Top5HTML =
			    CONCATENATEX(
			        _Top5,
			        VAR _rank = RANKX(_Top5, [@Rev],, DESC, Dense)
			        VAR _barW = DIVIDE([@Rev], _MaxRev) * _MaxBarPx
			        VAR _fmt  = IF([@Rev] >= 1000000,
			                       FORMAT([@Rev] / 1000000, "0.00") & "M",
			                       FORMAT([@Rev] / 1000, "#,0") & "K")
			        RETURN
			        "<div style='display:flex;align-items:center;gap:6px;margin-bottom:7px'>" &
			          "<span style='color:#aaa;font-size:10px;min-width:10px;text-align:right'>" & _rank & "</span>" &
			          "<span style='flex:1;font-size:11px;color:#333;white-space:nowrap;overflow:hidden'>"
			              & 'Fact'[distributor_name] & "</span>" &          -- ← REPLACE column
			          "<div style='width:" & _MaxBarPx & "px;background:#EDEBE5;border-radius:3px;height:5px;flex-shrink:0'>" &
			            "<div style='background:#C4C0B8;width:" & _barW & "px;height:5px;border-radius:3px'></div>" &
			          "</div>" &
			          "<span style='font-size:10px;color:#333;min-width:50px;text-align:right'>" & _fmt & "</span>" &
			        "</div>",
			        "",
			        [@Rev], DESC
			    )
			
			-- ③ Bottom 4 (remaining, ranked worst first)
			VAR _Bottom4 = TOPN(4, _All, [@Rev], ASC)
			
			VAR _Bottom4HTML =
			    CONCATENATEX(
			        _Bottom4,
			        VAR _rank = RANKX(_Bottom4, [@Rev],, ASC, Dense)
			        VAR _barW = DIVIDE([@Rev], _MaxRev) * _MaxBarPx
			        VAR _fmt  = IF([@Rev] >= 1000000,
			                       FORMAT([@Rev] / 1000000, "0.00") & "M",
			                       FORMAT([@Rev] / 1000, "#,0") & "K")
			        RETURN
			        "<div style='display:flex;align-items:center;gap:6px;margin-bottom:7px'>" &
			          "<span style='color:#aaa;font-size:10px;min-width:10px;text-align:right'>" & _rank & "</span>" &
			          "<span style='flex:1;font-size:11px;color:#333;white-space:nowrap;overflow:hidden'>"
			              & 'Fact'[distributor_name] & "</span>" &          -- ← REPLACE column
			          "<div style='width:" & _MaxBarPx & "px;background:#EDEBE5;border-radius:3px;height:5px;flex-shrink:0'>" &
			            "<div style='background:#C4C0B8;width:" & _barW & "px;height:5px;border-radius:3px'></div>" &
			          "</div>" &
			          "<span style='font-size:10px;color:#333;min-width:50px;text-align:right'>" & _fmt & "</span>" &
			        "</div>",
			        "",
			        [@Rev], ASC
			    )
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>" &
			
			  "<div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:12px'>" &
			    "<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222'>DISTRIBUTOR PERFORMANCE</span>" &
			    "<span style='font-size:10px;color:#aaa'>Sales value · AED</span>" &
			  "</div>" &
			
			  "<div style='font-size:9px;font-weight:700;letter-spacing:0.5px;color:#1A5C5A;margin-bottom:8px'>▲ TOP 5 PERFORMERS</div>" &
			  _Top5HTML &
			
			  "<div style='font-size:9px;font-weight:700;letter-spacing:0.5px;color:#8B1A1A;margin:12px 0 8px'>▼ BOTTOM 4 · ACTION REQUIRED</div>" &
			  _Bottom4HTML &
			
			"</div>"
			```
		lineageTag: 61425a98-68f4-4bd4-b58f-8cda8f9cf4a7

	measure 'KPI HTML - Revenue Trend' = ```
			
			
			VAR _YoY    = [Revenue YoY %]
			VAR _Sign   = IF(_YoY >= 0, "+", "")
			VAR _YoYTxt = _Sign & FORMAT(_YoY * 100, "0.0") & "% YoY"
			VAR _YoYBg  = IF(_YoY >= 0, "#E3EEE0", "#FCEAEA")
			VAR _YoYFg  = IF(_YoY >= 0, "#1A5C5A", "#8B1A1A")
			
			-- Chart canvas
			VAR _W     = 540   VAR _H     = 240
			VAR _PadL  = 38    VAR _PadR  = 8
			VAR _PadT  = 6     VAR _PadB  = 18
			VAR _PlotW = _W - _PadL - _PadR
			VAR _PlotH = _H - _PadT - _PadB
			VAR _XStep = DIVIDE(_PlotW, 11)
			
			-- Monthly revenue  ← REPLACE table/columns below
			
			VAR _Data =
			    ADDCOLUMNS(
			        GENERATESERIES(1,12,1),
			
			        "@R24",
			        VAR _Month = [Value]
			        RETURN
			        CALCULATE(
			            SUM('Fact'[Sales Amount]),
			            FILTER(
			                ALL('Dim_Date'),
			                'Dim_Date'[year] = 2024 &&
			                'Dim_Date'[month] = _Month
			            )
			        ),
			
			        "@R23",
			        VAR _Month2 = [Value]
			        RETURN
			        CALCULATE(
			            SUM('Fact'[Sales Amount]),
			            FILTER(
			                ALL('Dim_Date'),
			                'Dim_Date'[year] = 2023 &&
			                'Dim_Date'[month] = _Month2
			            )
			        )
			    )
			VAR _MaxRev = MAXX(_Data, MAX([@R24], [@R23]))
			VAR _MinRev = MINX(_Data, MIN([@R24], [@R23])) * 0.92   -- small padding below min
			
			-- SVG polyline point helpers
			VAR _Pts24 =
			    CONCATENATEX(
			        _Data,
			        VAR _x = _PadL + ([Value] - 1) * _XStep
			        VAR _y = _PadT + _PlotH
			              - DIVIDE(IF(ISBLANK([@R24]), _MinRev, [@R24]) - _MinRev, _MaxRev - _MinRev) * _PlotH
			        RETURN FORMAT(_x, "0.0") & "," & FORMAT(_y, "0.0"),
			        " ", [Value], ASC
			    )
			
			VAR _Pts23 =
			    CONCATENATEX(
			        _Data,
			        VAR _x = _PadL + ([Value] - 1) * _XStep
			        VAR _y = _PadT + _PlotH
			              - DIVIDE(IF(ISBLANK([@R23]), _MinRev, [@R23]) - _MinRev, _MaxRev - _MinRev) * _PlotH
			        RETURN FORMAT(_x, "0.0") & "," & FORMAT(_y, "0.0"),
			        " ", [Value], ASC
			    )
			
			-- Closed polygon for area fill
			VAR _BottomY = FORMAT(_PadT + _PlotH, "0")
			VAR _AreaPts = _Pts24
			    & " " & FORMAT(_PadL + 11 * _XStep, "0") & "," & _BottomY
			    & " " & FORMAT(_PadL, "0")                & "," & _BottomY
			
			-- December dot
			VAR _Dec24 = CALCULATE(SUM('Fact'[Sales Amount]), 'Dim_Date'[year]=2024, 'Dim_Date'[month]=12)  
			VAR _DotX  = _PadL + 11 * _XStep
			VAR _DotY  = _PadT + _PlotH
			           - DIVIDE(IF(ISBLANK(_Dec24), _MinRev, _Dec24) - _MinRev, _MaxRev - _MinRev) * _PlotH
			
			-- Y-axis labels
			VAR _MaxFmt = IF(_MaxRev>=1000000, FORMAT(_MaxRev/1000000,"0.#")&"M", FORMAT(_MaxRev/1000,"#,0")&"K")
			VAR _MinFmt = IF(_MinRev>=1000000, FORMAT(_MinRev/1000000,"0.#")&"M", FORMAT(_MinRev/1000,"#,0")&"K")
			
			-- Month labels
			VAR _MonthLbls =
			    CONCATENATEX(
			        GENERATESERIES(1, 12, 1),
			        VAR _x  = _PadL + ([Value] - 1) * _XStep
			        VAR _lbl = SWITCH([Value],1,"Jan",2,"Feb",3,"Mar",4,"Apr",5,"May",6,"Jun",
			                          7,"Jul",8,"Aug",9,"Sep",10,"Oct",11,"Nov",12,"Dec")
			        RETURN
			        "<text x='" & FORMAT(_x,"0") & "' y='" & FORMAT(_PadT + _PlotH + 12,"0") & "'" &
			        " text-anchor='middle' font-size='7.5' fill='#bbb'>" & _lbl & "</text>",
			        "", [Value], ASC
			    )
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>" &
			
			  "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:10px'>" &
			    "<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222'>REVENUE TREND · MONTH OVER MONTH</span>" &
			    "<span style='background:" & _YoYBg & ";color:" & _YoYFg & ";font-size:9px;font-weight:700;padding:3px 9px;border-radius:10px'>"
			        & _YoYTxt & "</span>" &
			  "</div>" &
			
			  "<svg width='" & _W & "' height='" & _H & "' viewBox='0 0 " & _W & " " & _H & "'>" &
			
			    -- Baseline + left axis
			    "<line x1='" & _PadL & "' y1='" & _PadT & "' x2='" & _PadL & "' y2='" & (_PadT+_PlotH) &
			    "' stroke='#E8E4DC' stroke-width='1'/>" &
			    "<line x1='" & _PadL & "' y1='" & (_PadT+_PlotH) & "' x2='" & (_W-_PadR) & "' y2='" & (_PadT+_PlotH) &
			    "' stroke='#E8E4DC' stroke-width='1'/>" &
			
			    -- Y labels
			    "<text x='" & (_PadL-4) & "' y='" & (_PadT+4) & "' text-anchor='end' font-size='8' fill='#bbb'>" & _MaxFmt & "</text>" &
			    "<text x='" & (_PadL-4) & "' y='" & (_PadT+_PlotH) & "' text-anchor='end' font-size='8' fill='#bbb'>" & _MinFmt & "</text>" &
			
			    -- Area fill under 2024 line
			    "<polygon points='" & _AreaPts & "' fill='#1A5C5A' fill-opacity='0.07'/>" &
			
			    -- 2023 dashed line
			    "<polyline points='" & _Pts23 & "' fill='none' stroke='#C8C4BC' stroke-width='1.5' stroke-dasharray='4 3'/>" &
			
			    -- 2024 solid line
			    "<polyline points='" & _Pts24 & "' fill='none' stroke='#1A5C5A' stroke-width='2'/>" &
			
			    -- December 2024 endpoint dot
			    "<circle cx='" & FORMAT(_DotX,"0") & "' cy='" & FORMAT(_DotY,"0.0") & "' r='4' fill='#1A5C5A'/>" &
			
			    -- Month labels
			    _MonthLbls &
			
			  "</svg>" &
			
			  -- Legend
			  "<div style='display:flex;gap:16px;margin-top:5px'>" &
			    "<div style='display:flex;align-items:center;gap:5px;font-size:9px;color:#555'>" &
			      "<svg width='18' height='8'><line x1='0' y1='4' x2='18' y2='4' stroke='#1A5C5A' stroke-width='2'/></svg>" &
			      "2024 (current)</div>" &
			    "<div style='display:flex;align-items:center;gap:5px;font-size:9px;color:#999'>" &
			      "<svg width='18' height='8'><line x1='0' y1='4' x2='18' y2='4' stroke='#C8C4BC'" &
			      " stroke-width='1.5' stroke-dasharray=""4 2""/></svg>" &
			      "2023 (prior year)</div>" &
			  "</div>" &
			
			"</div>"
			```
		lineageTag: b9a07c75-835c-4dd0-b2f3-89c6a9b1d99f

	measure 'Numeric Distribution %' =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT(Fact[Product_id]),
			        Fact[units_sold] > 0,
			        'Dim_Date'[year] = 2024
			    ),
			    CALCULATE(
			        DISTINCTCOUNT(Dim_Product[Product_id]),
			        'Dim_Date'[year] = 2024
			    )
			)
		lineageTag: e5840e0e-a4d4-430e-af6a-7207dd88ba5d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Out Rate %' =
			
			DIVIDE(
			    CALCULATE(COUNTROWS('Fact'), Fact[stock_available] = 0),
			    COUNTROWS('Fact')
			)
		lineageTag: e95d835c-2dda-4fb2-aeec-486be701711f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'E-Commerce Revenue' =
			
			CALCULATE([Total Revenue], Dim_channel[channel] = "E-Commerce")
		lineageTag: e01dc8c0-17af-466c-9f78-4b366cb97618

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'E-Commerce Revenue LY' =
			
			CALCULATE(
			    [Total Revenue],
			    SAMEPERIODLASTYEAR(Dim_Date[date]),
			    Dim_channel[channel] = "E-Commerce"
			)
		lineageTag: 2bc4d5d2-adbe-4ca5-8f87-28f078e867c3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'E-Commerce Growth %' =
			
			DIVIDE(
			    [E-Commerce Revenue] - [E-Commerce Revenue LY],
			    ABS([E-Commerce Revenue LY])
			)
		lineageTag: c8f4fd15-c69a-43fe-9b7b-fc76af6186dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Channel Revenue Share %' =
			
			DIVIDE(
			    [Total Revenue],
			    CALCULATE([Total Revenue], ALL(Dim_channel))
			)
		lineageTag: 84edae67-a0b2-4cfc-a718-492324b3649f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Delivery Days' = AVERAGE(Fact[delivery_days])
		lineageTag: 20f6abe0-b1c3-416e-818c-97a459bc7f03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Coverage Days' =
			
			AVERAGEX(
			    'Fact',
			    DIVIDE(Fact[stock_available], Fact[units_sold]) * 7
			)
		lineageTag: 725c9da4-e5f1-44ab-8eb4-7873346cbaa0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI HTML - Numeric Distribution %' =
			
			VAR _Status     = [Numeric Distribution %]
			VAR _PriorAvg = [Numeric Distribution % 2023]
			VAR _Delta    = DIVIDE ( _Status - _PriorAvg, _PriorAvg, 0 )
			VAR _Color    = IF ( _Delta >= 0, "#2C5C3C", "#8C2E20" )
			VAR _Bg       = IF ( _Delta >= 0, "#E7F2EB", "#F8E8E4" )
			VAR _Sign     = IF ( _Delta >= 0, "+", "-" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #9B870C;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>"&
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>Numeric Distribution %</div>" &
			"<div style='font-size:28px;font-weight:700;color:" & _Color & ";line-height:1;'>" & FORMAT ( _Status, "0.0%" ) & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>of total SKU universe active</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Sign & FORMAT ( ABS ( _Delta ), "0.0%" ) & " vs 2023</div>" &
			"</div>"
		lineageTag: cde2c4bf-03e9-4afa-aba2-69320ee832d2

	measure 'Numeric Distribution % 2023' =
			
			DIVIDE(
			    CALCULATE(
			        DISTINCTCOUNT(Fact[Product_id]),
			        Fact[units_sold] > 0,
			        'Dim_Date'[year] = 2023
			    ),
			    CALCULATE(
			        DISTINCTCOUNT(Dim_Product[Product_id]),
			        'Dim_Date'[year] = 2023
			    )
			)
		lineageTag: 3a5f12a5-d36c-404b-afec-ca831568c3b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI HTML - Stock Out Rate %' = ```
			
			VAR _Status   = [stockout Status] 
			VAR _AchPct   = [Stock Out Rate %]
			VAR _Color    = SWITCH ( TRUE (), _AchPct >= 1, "#8C2E20", _AchPct >= 0.9, "#8C5C0D", "#2C5C3C" )
			VAR _Bg       = SWITCH ( TRUE (), _AchPct >= 1, "#F8E8E4", _AchPct >= 0.9, "#FAF1DF", "#E7F2EB" )
			VAR _Accent   = SWITCH ( TRUE (), _AchPct >= 1, "#B23E2B", _AchPct >= 0.9, "#BE7A12", "#3F7D52" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid " & _Accent & ";
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>Stock Out Rate % </div>" &
			"<div style='font-size:28px;font-weight:700;color:" & _Color & ";line-height:1;'>" & FORMAT ( _AchPct, "0.0%" ) & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>of outlet-SKU combos with 0 stock</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Status & "</div>" &
			"</div>" 
			```
		lineageTag: 73c20cde-9d22-44f8-8dbd-206b20b252f4

	measure 'stockout Status' = ```
			
			SWITCH (
			    TRUE (),
			    [Stock Out Rate %] >= 1,    "High Risk",
			    [Stock Out Rate %] >= 0.5,  "Moderate",
			    "Low Risk"
			)
			
			```
		lineageTag: 155664b7-c7d8-453c-baca-7490408bacf5

	measure 'KPI HTML - E-Commerce Growth %' = ```
			
			VAR _Status   = [E-Commerce Revenue LY] 
			VAR _AchPct   = [E-Commerce Growth %]
			VAR _Color    = SWITCH ( TRUE (), _AchPct >= 1, "#8C2E20", _AchPct >= 0.9, "#8C5C0D", "#2C5C3C" )
			VAR _Bg       = SWITCH ( TRUE (), _AchPct >= 1, "#F8E8E4", _AchPct >= 0.9, "#FAF1DF", "#E7F2EB" )
			VAR _Accent   = SWITCH ( TRUE (), _AchPct >= 1, "#B23E2B", _AchPct >= 0.9, "#BE7A12", "#3F7D52" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid " & _Accent & ";
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>E-Commerce Growth </div>" &
			"<div style='font-size:28px;font-weight:700;color:" & _Color & ";line-height:1;'>" & FORMAT ( _AchPct, "0.0%" ) & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>YoY revenue growth 2023→2024</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Status & "</div>" &
			"</div>" 
			```
		lineageTag: 8a760777-0795-4981-9121-07cc0df0750c

	measure 'Channel Revenue Share % Label' =
			
			FORMAT([Channel Revenue Share %], "0.0%")
		lineageTag: 36bda19b-332e-4131-8c16-6c163f1a6026

	measure 'HTML - Revenue By Channel Region' = ```
			
			
			VAR CentralRetail =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-Central",
			        Fact[channel] = "Retail",
			        Dim_Date[year] = 2024
			    )
			VAR CentralDiscount =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-Central",
			        Fact[channel] = "Discount",
			        Dim_Date[year] = 2024
			    )
			VAR CentralEcom =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-Central",
			        Fact[channel] = "E-Commerce",
			        Dim_Date[year] = 2024
			    )
			VAR CentralTotal = CentralRetail + CentralDiscount + CentralEcom
			
			VAR NorthRetail =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-North",
			        Fact[channel] = "Retail",
			        Dim_Date[year] = 2024
			    )
			VAR NorthDiscount =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-North",
			        Fact[channel] = "Discount",
			        Dim_Date[year] = 2024
			    )
			VAR NorthEcom =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-North",
			        Fact[channel] = "E-Commerce",
			        Dim_Date[year] = 2024
			    )
			VAR NorthTotal = NorthRetail + NorthDiscount + NorthEcom
			
			VAR SouthRetail =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-South",
			        Fact[channel] = "Retail",
			        Dim_Date[year] = 2024
			    )
			VAR SouthDiscount =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-South",
			        Fact[channel] = "Discount",
			        Dim_Date[year] = 2024
			    )
			VAR SouthEcom =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        Fact[region] = "PL-South",
			        Fact[channel] = "E-Commerce",
			        Dim_Date[year] = 2024
			    )
			VAR SouthTotal = SouthRetail + SouthDiscount + SouthEcom
			
			-- Max region total → used to scale all bars proportionally
			VAR MaxVal = MAXX( { CentralTotal, NorthTotal, SouthTotal }, [Value] )
			
			-- Max bar width in pixels (adjust if your visual is wider/narrower)
			VAR BarWidth = 280
			
			-- Bar segment widths as integers
			VAR CR = INT( DIVIDE(CentralRetail,  MaxVal) * BarWidth )
			VAR CD = INT( DIVIDE(CentralDiscount, MaxVal) * BarWidth )
			VAR CE = INT( DIVIDE(CentralEcom,    MaxVal) * BarWidth )
			
			VAR NR = INT( DIVIDE(NorthRetail,    MaxVal) * BarWidth )
			VAR ND = INT( DIVIDE(NorthDiscount,  MaxVal) * BarWidth )
			VAR NE = INT( DIVIDE(NorthEcom,      MaxVal) * BarWidth )
			
			VAR SR = INT( DIVIDE(SouthRetail,    MaxVal) * BarWidth )
			VAR SD = INT( DIVIDE(SouthDiscount,  MaxVal) * BarWidth )
			VAR SE = INT( DIVIDE(SouthEcom,      MaxVal) * BarWidth )
			
			-- Dynamic insight: find region with highest E-Commerce share
			VAR CentralEcomShare = DIVIDE(CentralEcom, CentralTotal)
			VAR NorthEcomShare   = DIVIDE(NorthEcom,   NorthTotal)
			VAR SouthEcomShare   = DIVIDE(SouthEcom,   SouthTotal)
			
			VAR TopEcomRegion =
			    SWITCH(
			        TRUE(),
			        CentralEcomShare >= NorthEcomShare && CentralEcomShare >= SouthEcomShare, "Central",
			        NorthEcomShare   >= SouthEcomShare, "North",
			        "South"
			    )
			VAR TopEcomShare =
			    SWITCH(
			        TopEcomRegion,
			        "Central", CentralEcomShare,
			        "North",   NorthEcomShare,
			        SouthEcomShare
			    )
			
			RETURN
			
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			padding:16px 18px;
			background:#FFFFFF;
			border-radius:10px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:18px;'>
			<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222;text-transform:uppercase;'>Revenue by Channel · per Region</span>
			<span style='font-size:10px;color:#aaa;'>Sales value — AED</span>
			</div>
			
			<div style='display:flex;align-items:center;margin-bottom:10px;'>
			<div style='width:52px;font-size:11px;color:#333;font-weight:500;'>Central</div>
			<div style='display:flex;height:14px;border-radius:2px;overflow:hidden;background:#f0f0f0;'>
			<div style='width:" & CR & "px;background:#1F6B4A;'></div>
			<div style='width:" & CD & "px;background:#3F8DB5;'></div>
			<div style='width:" & CE & "px;background:#D5B314;'></div>
			</div>
			<div style='margin-left:8px;font-size:11px;font-weight:700;color:#222;'>"
			& FORMAT(CentralTotal / 1000000, "0.0") & "M</div>
			</div>
			
			<div style='display:flex;align-items:center;margin-bottom:10px;'>
			<div style='width:52px;font-size:11px;color:#333;font-weight:500;'>North</div>
			<div style='display:flex;height:14px;border-radius:2px;overflow:hidden;background:#f0f0f0;'>
			<div style='width:" & NR & "px;background:#1F6B4A;'></div>
			<div style='width:" & ND & "px;background:#3F8DB5;'></div>
			<div style='width:" & NE & "px;background:#D5B314;'></div>
			</div>
			<div style='margin-left:8px;font-size:11px;font-weight:700;color:#222;'>"
			& FORMAT(NorthTotal / 1000000, "0.0") & "M</div>
			</div>
			
			<div style='display:flex;align-items:center;margin-bottom:16px;'>
			<div style='width:52px;font-size:11px;color:#333;font-weight:500;'>South</div>
			<div style='display:flex;height:14px;border-radius:2px;overflow:hidden;background:#f0f0f0;'>
			<div style='width:" & SR & "px;background:#1F6B4A;'></div>
			<div style='width:" & SD & "px;background:#3F8DB5;'></div>
			<div style='width:" & SE & "px;background:#D5B314;'></div>
			</div>
			<div style='margin-left:8px;font-size:11px;font-weight:700;color:#222;'>"
			& FORMAT(SouthTotal / 1000000, "0.0") & "M</div>
			</div>
			
			<div style='display:flex;gap:16px;font-size:10px;color:#555;margin-bottom:12px;'>
			<span><span style='color:#1F6B4A;font-size:13px;'>■</span> Retail</span>
			<span><span style='color:#3F8DB5;font-size:13px;'>■</span> Discount</span>
			<span><span style='color:#D5B314;font-size:13px;'>■</span> E-Commerce</span>
			</div>
			
			<div style='border:1px solid #C3E0CC;background:#EDF7EF;padding:6px 9px;
			font-size:10px;border-radius:4px;color:#2E6D48;font-weight:500;'>
			📌 E-Commerce highest share in " & TopEcomRegion & " (" &
			FORMAT(TopEcomShare, "0%") &
			") — signals digital-first behaviour shift
			</div>
			
			</div>"
			
			```
		lineageTag: 703bbb86-e73c-4b00-baa3-05502422bcb2

	measure 'Revenue AED' =
			
			SUM ( 'Fact'[Sales Amount] )
		lineageTag: c319c06a-3e17-40dc-80a9-62a70abbebad

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue - Retail' =
			
			CALCULATE (
			    [Revenue AED],
			    Dim_channel[channel] = "Retail"
			)
		lineageTag: 8e2a0c49-11ff-434f-8d4c-29b69073e4e5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue - Discount' =
			
			CALCULATE (
			    [Revenue AED],
			    Dim_channel[channel] = "Discount"
			)
		lineageTag: 23305518-e17d-49f2-8058-115cc1bba5ed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue - E-Commerce' =
			
			CALCULATE (
			    [Revenue AED],
			    Dim_channel[channel] = "E-Commerce"
			)
		lineageTag: e6e43a2c-0b00-4eb8-bd08-1a5b882b4415

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'HTML - Stock Availability vs Sales Velocity' = ```
			
			
			-- Summarise one row per SKU: avg stock available + total units sold for 2024
			VAR _Data =
			    ADDCOLUMNS(
			        SUMMARIZE('Fact', Fact[sku]),
			        "@Stock", CALCULATE(AVERAGE(Fact[stock_available]), Dim_Date[year] = 2024),
			        "@Sales", CALCULATE(SUM(Fact[units_sold]),          Dim_Date[year] = 2024)
			    )
			
			-- Remove any SKUs with no 2024 data
			VAR _Clean =
			    FILTER(_Data, NOT ISBLANK([@Stock]) && NOT ISBLANK([@Sales]) && [@Sales] > 0)
			
			-- Axis bounds
			VAR _MinStock = MINX(_Clean, [@Stock])
			VAR _MaxStock = MAXX(_Clean, [@Stock])
			
			VAR _MinSales = MINX(_Clean, [@Sales])
			VAR _MaxSales = MAXX(_Clean, [@Sales])
			
			-- Quadrant midpoints (average of each axis)
			VAR _AvgStock = AVERAGEX(_Clean, [@Stock])
			VAR _AvgSales = AVERAGEX(_Clean, [@Sales])
			
			-- SVG canvas
			VAR _W    = 380
			VAR _H    = 170
			VAR _PadL = 42
			VAR _PadR = 10
			VAR _PadT = 24
			VAR _PadB = 28
			VAR _PlotW = _W - _PadL - _PadR
			VAR _PlotH = _H - _PadT - _PadB
			
			-- Quadrant divider pixel positions
			VAR _QX =
			    _PadL +
			    INT(
			        DIVIDE(
			            _AvgSales - _MinSales,
			            _MaxSales - _MinSales
			        ) * _PlotW
			    )
			
			VAR _QY =
			    _PadT +
			    INT(
			        _PlotH -
			        DIVIDE(
			            _AvgStock - _MinStock,
			            _MaxStock - _MinStock
			        ) * _PlotH
			    )
			
			-- Y-axis tick labels
			VAR _YMax = IF(_MaxStock >= 1000, FORMAT(_MaxStock/1000,"0.0") & "K", FORMAT(_MaxStock,"0"))
			VAR _YMid = IF(_AvgStock >= 1000, FORMAT(_AvgStock/1000,"0.0") & "K", FORMAT(_AvgStock,"0"))
			
			-- X-axis tick labels
			VAR _XMax = IF(_MaxSales >= 1000, FORMAT(_MaxSales/1000,"0.0") & "K", FORMAT(_MaxSales,"0"))
			VAR _XMid = IF(_AvgSales >= 1000, FORMAT(_AvgSales/1000,"0.0") & "K", FORMAT(_AvgSales,"0"))
			
			-- Generate one SVG circle per SKU
			VAR _Dots =
			    CONCATENATEX(
			        _Clean,
			        VAR _cx =
			    _PadL +
			    INT(
			        DIVIDE(
			            [@Sales] - _MinSales,
			            _MaxSales - _MinSales
			        ) * _PlotW
			    )
			
			    VAR _cy =
			    _PadT +
			    INT(
			        _PlotH -
			        DIVIDE(
			            [@Stock] - _MinStock,
			            _MaxStock - _MinStock
			        ) * _PlotH
			    )
			        VAR _clr =
			            SWITCH(
			                TRUE(),
			                [@Stock] >= _AvgStock && [@Sales] >= _AvgSales, "#1B9E75",  -- Healthy
			                [@Stock] <  _AvgStock && [@Sales] >= _AvgSales, "#E74C3C",  -- Stockout risk
			                [@Stock] >= _AvgStock && [@Sales] <  _AvgSales, "#8E44AD",  -- Dead inventory
			                "#F0A500"                                                     -- Review
			            )
			        RETURN
			        "<circle cx='" & _cx & "' cy='" & _cy &
			        "' r='5' fill='" & _clr & "' fill-opacity='0.75' stroke='#fff' stroke-width='0.8'>" &
			        "<title>" & Fact[sku] & "</title></circle>",
			        "",
			        [@Sales], ASC
			    )
			
			RETURN
			
			"<div style='font-family:Segoe UI,Arial,sans-serif;padding:16px 18px;
			background:#FFFFFF;border-radius:10px;height:90%;box-sizing:border-box;'>
			
			<div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:10px;'>
			<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222;text-transform:uppercase;'>
			Stock Availability vs Sales Velocity · By SKU
			</span>
			<span style='font-size:10px;color:#aaa;'>Stockout risk matrix</span>
			</div>
			
			<svg width='100%' viewBox='0 0 " & _W & " " & _H & "' xmlns='http://www.w3.org/2000/svg'>
			
			  <!-- Plot area background -->
			  <rect x='" & _PadL & "' y='" & _PadT & "'
			        width='" & _PlotW & "' height='" & _PlotH & "'
			        fill='#FAFAFA' stroke='#EBEBEB' stroke-width='1'/>
			
			  <!-- Quadrant dividers (dashed) -->
			  <line x1='" & _QX & "' y1='" & _PadT & "'
			        x2='" & _QX & "' y2='" & (_PadT + _PlotH) & "'
			        stroke='#CCCCCC' stroke-width='1' stroke-dasharray='4 3'/>
			  <line x1='" & _PadL & "' y1='" & _QY & "'
			        x2='" & (_PadL + _PlotW) & "' y2='" & _QY & "'
			        stroke='#CCCCCC' stroke-width='1' stroke-dasharray='4 3'/>
			
			  <!-- Quadrant corner labels -->
			  <text x='" & (_PadL + 4) & "' y='" & (_PadT + 10) & "'
			        font-size='7' fill='#CCCCCC' font-style='italic'>High Stock · Low Sales</text>
			
			  <text x='" & (_PadL + _PlotW - 4) & "' y='" & (_PadT + 10) & "'
			        font-size='7' fill='#BBBBBB' font-style='italic' text-anchor='end'>Sweet spot</text>
			
			  <text x='" & (_PadL + 4) & "' y='" & (_PadT + _PlotH - 5) & "'
			        font-size='7' fill='#E74C3C' fill-opacity='0.55' font-style='italic'>Stockout risk</text>
			
			  <text x='" & (_PadL + _PlotW - 4) & "' y='" & (_PadT + _PlotH - 5) & "'
			        font-size='7' fill='#8E44AD' fill-opacity='0.55' font-style='italic' text-anchor='end'>Dead inventory</text>
			
			  <!-- Y axis line + labels -->
			  <line x1='" & _PadL & "' y1='" & _PadT & "'
			        x2='" & _PadL & "' y2='" & (_PadT + _PlotH) & "'
			        stroke='#CCCCCC' stroke-width='1'/>
			
			  <text x='" & (_PadL - 4) & "' y='" & (_PadT + 4) & "'
			        text-anchor='end' font-size='7' fill='#AAAAAA'>" & _YMax & "</text>
			
			  <text x='" & (_PadL - 4) & "' y='" & _QY & "'
			        text-anchor='end' font-size='7' fill='#AAAAAA' dy='3'>" & _YMid & "</text>
			
			  <text x='" & (_PadL - 4) & "' y='" & (_PadT + _PlotH) & "'
			        text-anchor='end' font-size='7' fill='#AAAAAA'>0</text>
			
			  <!-- Y axis title (rotated) -->
			  <text x='10' y='" & (_PadT + _PlotH / 2) & "'
			        text-anchor='middle' font-size='7.5' fill='#999999'
			        transform='rotate(-90 10 " & (_PadT + _PlotH / 2) & ")'>Stock Available</text>
			
			  <!-- X axis line + labels -->
			  <line x1='" & _PadL & "' y1='" & (_PadT + _PlotH) & "'
			        x2='" & (_PadL + _PlotW) & "' y2='" & (_PadT + _PlotH) & "'
			        stroke='#CCCCCC' stroke-width='1'/>
			
			  <text x='" & _PadL & "' y='" & (_PadT + _PlotH + 14) & "'
			        text-anchor='middle' font-size='7' fill='#AAAAAA'>0</text>
			
			  <text x='" & _QX & "' y='" & (_PadT + _PlotH + 14) & "'
			        text-anchor='middle' font-size='7' fill='#AAAAAA'>" & _XMid & "</text>
			
			  <text x='" & (_PadL + _PlotW) & "' y='" & (_PadT + _PlotH + 14) & "'
			        text-anchor='end' font-size='7' fill='#AAAAAA'>" & _XMax & "</text>
			
			  <text x='" & (_PadL + _PlotW / 2) & "' y='" & (_PadT + _PlotH + 24) & "'
			        text-anchor='middle' font-size='7.5' fill='#999999'>Units Sold →</text>
			
			  <!-- SKU dots -->
			  " & _Dots & "
			
			</svg>
			
			<!-- Legend -->
			<div style='display:flex;gap:14px;font-size:10px;color:#555;margin-top:2px;flex-wrap:wrap;'>
			<span><span style='color:#1B9E75;font-size:14px;'>●</span> Healthy</span>
			<span><span style='color:#E74C3C;font-size:14px;'>●</span> Stockout risk</span>
			<span><span style='color:#8E44AD;font-size:14px;'>●</span> Dead stock</span>
			<span><span style='color:#F0A500;font-size:14px;'>●</span> Review</span>
			</div>
			
			</div>"
			
			```
		lineageTag: d761a40e-63d7-4e9e-82c0-9f70f1f96b68

	measure HTML_EcomRevTrend =
			
			
			-- ── CHART DIMENSIONS ────────────────────────────────────────────────
			VAR _W  = 640
			VAR _H  = 220
			VAR _PL = 12         -- padding left
			VAR _PR = 12         -- padding right
			VAR _PT = 14         -- padding top
			VAR _PB = 30         -- padding bottom (space for x-axis labels)
			VAR _CW = _W - _PL - _PR     -- chart draw width
			VAR _CH = _H - _PT - _PB     -- chart draw height
			
			-- ── RAW DATA: E-Commerce revenue, monthly, all 3 years ──────────────
			-- SUMMARIZE groups the E-Com filtered Fact by year + month from Dim_Date
			-- ADDCOLUMNS then computes the actual SUM per group via context transition
			VAR _Raw =
			    ADDCOLUMNS(
			        SUMMARIZE(
			            CALCULATETABLE( 'Fact', Dim_channel[channel] = "E-Commerce" ),
			            Dim_Date[year],
			            Dim_Date[month]
			        ),
			        "Rev",
			        CALCULATE(
			            SUM( Fact[Sales Amount] ),
			            Dim_channel[channel] = "E-Commerce"
			        )
			    )
			
			-- Scale anchor: highest monthly value across all 3 years
			VAR _MaxRev = MAXX( _Raw, [Rev] )
			VAR _Sc     = IF( _MaxRev = 0, 1, _MaxRev )
			
			-- Split by year for separate polylines
			VAR _D22 = FILTER( _Raw, [year] = 2022 )
			VAR _D23 = FILTER( _Raw, [year] = 2023 )
			VAR _D24 = FILTER( _Raw, [year] = 2024 )
			
			-- ── POLYLINE COORDINATE BUILDER ──────────────────────────────────────
			-- X: maps month 1→12 across chart width
			-- Y: maps Rev to chart height (SVG y=0 is top, so we invert)
			
			VAR _P22 =
			    CONCATENATEX(
			        ADDCOLUMNS( _D22,
			            "PX", FORMAT( _PL + ( ( [month] - 1 ) / 11 ) * _CW, "0.0" ),
			            "PY", FORMAT( _PT + _CH - ( [Rev] / _Sc ) * _CH,    "0.0" )
			        ),
			        [PX] & "," & [PY],
			        " ",
			        [month], ASC
			    )
			
			VAR _P23 =
			    CONCATENATEX(
			        ADDCOLUMNS( _D23,
			            "PX", FORMAT( _PL + ( ( [month] - 1 ) / 11 ) * _CW, "0.0" ),
			            "PY", FORMAT( _PT + _CH - ( [Rev] / _Sc ) * _CH,    "0.0" )
			        ),
			        [PX] & "," & [PY],
			        " ",
			        [month], ASC
			    )
			
			VAR _P24 =
			    CONCATENATEX(
			        ADDCOLUMNS( _D24,
			            "PX", FORMAT( _PL + ( ( [month] - 1 ) / 11 ) * _CW, "0.0" ),
			            "PY", FORMAT( _PT + _CH - ( [Rev] / _Sc ) * _CH,    "0.0" )
			        ),
			        [PX] & "," & [PY],
			        " ",
			        [month], ASC
			    )
			
			-- ── X-AXIS MONTH LABELS (Jan, Mar, May, Jul, Sep, Nov, Dec) ─────────
			VAR _XLabels =
			    CONCATENATEX(
			        FILTER(
			            ADDCOLUMNS(
			                GENERATESERIES( 1, 12, 1 ),
			                "Lbl",  SWITCH( [Value],
			                            1,"Jan",  2,"Feb",  3,"Mar",  4,"Apr",
			                            5,"May",  6,"Jun",  7,"Jul",  8,"Aug",
			                            9,"Sep",  10,"Oct", 11,"Nov", 12,"Dec" ),
			                "Show", SWITCH( [Value], 1,1, 3,1, 5,1, 7,1, 9,1, 11,1, 12,1, 0 ),
			                "XP",   _PL + ( ( [Value] - 1 ) / 11 ) * _CW
			            ),
			            [Show] = 1
			        ),
			        "<text x='" & FORMAT( [XP], "0.0" ) & "'
			               y='" & FORMAT( _PT + _CH + 18, "0" ) & "'
			               text-anchor='middle'
			               font-size='9.5' fill='#aaa'>" & [Lbl] & "</text>",
			        "",
			        [Value], ASC
			    )
			
			-- ── HORIZONTAL GRID LINES (4 lines across chart) ────────────────────
			VAR _Grids =
			    CONCATENATEX(
			        ADDCOLUMNS(
			            GENERATESERIES( 1, 4, 1 ),
			            "GY", FORMAT( _PT + ( [Value] / 4 ) * _CH, "0.0" )
			        ),
			        "<line x1='" & FORMAT( _PL, "0" ) & "' y1='" & [GY] & "'
			               x2='" & FORMAT( _PL + _CW, "0" ) & "' y2='" & [GY] & "'
			               stroke='#efefef' stroke-width='1'/>",
			        "",
			        [Value], ASC
			    )
			
			-- ── FOOTER: Dynamic E-Com growth 2022→2024 for Central ──────────────
			VAR _EC22C =
			    CALCULATE( SUM( Fact[Sales Amount] ),
			        Dim_channel[channel] = "E-Commerce",
			        Dim_Date[year]       = 2022,
			        Dim_region[region]   = "Central" )
			VAR _EC24C =
			    CALCULATE( SUM( Fact[Sales Amount] ),
			        Dim_channel[channel] = "E-Commerce",
			        Dim_Date[year]       = 2024,
			        Dim_region[region]   = "Central" )
			VAR _Grw   = IF( _EC22C <> 0, ( _EC24C - _EC22C ) / _EC22C * 100, BLANK() )
			VAR _GrwSt = FORMAT( _Grw, "+0.0;-0.0" ) & "%"
			
			-- ── ASSEMBLE HTML ────────────────────────────────────────────────────
			RETURN
			"<div style='font-family:Segoe UI,sans-serif;padding:12px 14px;
			             background:#fff;border-radius:6px;box-sizing:border-box;'>
			
			  <!-- HEADER ROW -->
			  <div style='display:flex;justify-content:space-between;
			              align-items:baseline;margin-bottom:6px;'>
			    <span style='font-size:11px;font-weight:700;
			                 letter-spacing:.07em;color:#1a1a1a;'>
			      E-COMMERCE CHANNEL · REVENUE TREND
			    </span>
			    <span style='font-size:10px;color:#aaa;'>Month over month — AED</span>
			  </div>
			
			  <!-- LEGEND -->
			  <div style='display:flex;gap:18px;margin-bottom:4px;'>
			    <span style='font-size:10px;color:#14532d;font-weight:700;'>—— 2024</span>
			    <span style='font-size:10px;color:#0e7490;'>—— 2023</span>
			    <span style='font-size:10px;color:#bbb;'>- - 2022</span>
			  </div>
			
			  <!-- SVG CHART -->
			  <svg width='100%' viewBox='0 0 " & FORMAT(_W,"0") & " " & FORMAT(_H,"0") & "'
			       xmlns='http://www.w3.org/2000/svg'>
			
			    " & _Grids & "
			
			    <!-- 2022: light dashed -->
			    <polyline points='" & _P22 & "'
			      fill='none' stroke='#d1d5db' stroke-width='1.5' stroke-dasharray='5,3'/>
			
			    <!-- 2023: teal solid -->
			    <polyline points='" & _P23 & "'
			      fill='none' stroke='#0e7490' stroke-width='2'/>
			
			    <!-- 2024: dark green bold -->
			    <polyline points='" & _P24 & "'
			      fill='none' stroke='#14532d' stroke-width='3'/>
			
			    " & _XLabels & "
			
			  </svg>
			
			  <!-- INSIGHT CALLOUT -->
			  <div style='margin-top:4px;padding:5px 10px;
			              background:#fffbeb;border-left:3px solid #d97706;
			              font-size:10px;color:#555;border-radius:0 3px 3px 0;'>
			    ✦ E-Commerce grew " & _GrwSt & " in Central 2022–2024
			      — separate channel investment case
			  </div>
			
			</div>"
		lineageTag: bc26a9cb-58bd-4263-89f9-805bc6a607cc

	measure HTML_AvgDeliveryRegion =
			
			
			-- ── CONFIG ──────────────────────────────────────────────────────────
			VAR _Target   = 2     -- target delivery days (hardcoded; adjust if from Dim_Target)
			VAR _MaxScale = 6.0      -- axis ceiling (keeps bar proportions stable across refreshes)
			VAR _BarMaxW  = 420      -- max bar pixel width in SVG
			VAR _BarH     = 22       -- bar height in px
			VAR _LabelW   = 62       -- region label column width
			VAR _RowGap   = 20       -- vertical gap between bar rows
			VAR _SVGW     = _LabelW + _BarMaxW + 24
			
			-- ── DATA: average delivery days per region ───────────────────────────
			VAR _RegData =
			    ADDCOLUMNS(
			        VALUES( Dim_region[region] ),
			        "AvgDel", CALCULATE( AVERAGE( Fact[delivery_days] ) )
			    )
			
			-- ── ENRICH: bar width, rank (for row order), color, label ───────────
			-- Color logic:
			--   Green  = on/under target
			--   Orange = up to 10% over target
			--   Red    = more than 10% over target
			VAR _Enriched =
			    ADDCOLUMNS(
			        _RegData,
			        "BarW",  MIN( [AvgDel] / _MaxScale * _BarMaxW,  _BarMaxW ),
			        "Rank",  RANKX( _RegData, [AvgDel],, DESC ),     -- highest del days = row 1
			        "Color", IF( [AvgDel] <= _Target,                "#166534",
			                 IF( [AvgDel] <= _Target * 1.10,         "#c2410c",
			                                                          "#b91c1c" ) ),
			        "Lbl",   FORMAT( [AvgDel], "0.0" ) & "d"
			    )
			
			-- ── FINAL PASS: add pixel Y positions (depends on Rank) ──────────────
			VAR _WithPos =
			    ADDCOLUMNS(
			        _Enriched,
			        "RowY",  ( [Rank] - 1 ) * _RowGap + 4,
			        "TextY", ( [Rank] - 1 ) * _RowGap + 4 + _BarH - 6
			    )
			
			-- ── SVG HEIGHT ────────────────────────────────────────────────────────
			VAR _NumReg = COUNTROWS( _RegData )
			VAR _SVGH = _NumReg * _RowGap + 10
			
			-- ── TARGET LINE X position ───────────────────────────────────────────
			VAR _TargetX = FORMAT( _LabelW + ( _Target / _MaxScale ) * _BarMaxW, "0.0" )
			
			-- ── BAR ROWS ─────────────────────────────────────────────────────────
			VAR _Bars =
			    CONCATENATEX(
			        _WithPos,
			        -- Region label
			        "<text x='0' y='" & FORMAT( [TextY], "0" ) & "'
			               font-size='11' font-weight='600' fill='#444'>" & [region] & "</text>"
			
			        -- Background track
			        & "<rect x='" & FORMAT( _LabelW, "0" ) & "'
			                y='" & FORMAT( [RowY], "0" ) & "'
			                width='" & FORMAT( _BarMaxW, "0" ) & "'
			                height='" & FORMAT( _BarH, "0" ) & "'
			                fill='#f3f4f6' rx='3'/>"
			
			        -- Coloured bar
			        & "<rect x='" & FORMAT( _LabelW, "0" ) & "'
			                y='" & FORMAT( [RowY], "0" ) & "'
			                width='" & FORMAT( [BarW], "0.0" ) & "'
			                height='" & FORMAT( _BarH, "0" ) & "'
			                fill='" & [Color] & "' rx='3'/>"
			
			        -- Value label inside bar
			        & "<text x='" & FORMAT( _LabelW + 8, "0" ) & "'
			                y='" & FORMAT( [TextY], "0" ) & "'
			                font-size='11' font-weight='700' fill='#fff'>" & [Lbl] & "</text>",
			
			        "",
			        [AvgDel], DESC       -- Central (highest) first
			    )
			
			-- ── FOOTER: dynamic on-track region name ─────────────────────────────
			VAR _OnTrackNames =
			    CONCATENATEX( FILTER( _RegData, [AvgDel] <= _Target ), [region], ", " )
			VAR _OnTrackCount =
			    COUNTROWS( FILTER( _RegData, [AvgDel] <= _Target ) )
			VAR _FooterTxt =
			    "| Target = " & FORMAT( _Target, "0.0" ) & "d  ("
			    & _OnTrackNames
			    & " only region" & IF( _OnTrackCount = 1, "", "s" ) & " on track)"
			
			-- ── ASSEMBLE HTML ────────────────────────────────────────────────────
			RETURN
			"<div style='font-family:Segoe UI,sans-serif;padding:12px 14px;
			             background:#fff;border-radius:6px;box-sizing:border-box;'>
			
			  <!-- HEADER ROW -->
			  <div style='display:flex;justify-content:space-between;
			              align-items:baseline;margin-bottom:12px;'>
			    <span style='font-size:11px;font-weight:700;
			                 letter-spacing:.07em;color:#1a1a1a;'>
			      AVG DELIVERY DAYS · BY REGION
			    </span>
			    <span style='font-size:10px;color:#aaa;'>
			      Target: " & FORMAT( _Target, "0.0" ) & " days
			    </span>
			  </div>
			
			  <!-- SVG BAR CHART -->
			  <svg width='100%'
			       viewBox='0 0 " & FORMAT( _SVGW, "0" ) & " " & FORMAT( _SVGH, "0" ) & "'
			       xmlns='http://www.w3.org/2000/svg'>
			
			    " & _Bars & "
			
			    <!-- Dashed target line -->
			    <line x1='" & _TargetX & "' y1='0'
			          x2='" & _TargetX & "' y2='" & FORMAT( _SVGH, "0" ) & "'
			          stroke='#9ca3af' stroke-width='1.5' stroke-dasharray='4,3'/>
			
			  </svg>
			
			  <!-- INSIGHT FOOTER -->
			  <div style='margin-top:6px;padding:5px 10px;
			              background:#f9fafb;border-left:3px solid #9ca3af;
			              font-size:10px;color:#6b7280;border-radius:0 3px 3px 0;'>
			    " & _FooterTxt & "
			  </div>
			
			</div>"
		lineageTag: 294a501d-f05d-44a8-bae1-6eb4f042a818

	measure HTML_SKUChannelPerf =
			
			
			VAR _ChanR = "Retail"
			VAR _ChanE = "E-Commerce"
			VAR _ChanD = "Discount"
			VAR _TopN  = 8
			
			-- TOP N SKUs by total revenue
			VAR _AllSKU =
			    ADDCOLUMNS(
			        VALUES( Dim_Product[Product_id] ),
			        "TotalRev", CALCULATE( SUM( Fact[Sales Amount] ) )
			    )
			
			VAR _TopSKUs =
			    TOPN( _TopN, _AllSKU, [TotalRev], DESC )
			
			-- Channel revenue per SKU
			VAR _Pivot =
			    ADDCOLUMNS(
			        _TopSKUs,
			        "RevR", CALCULATE( SUM( Fact[Sales Amount] ), Dim_channel[channel] = _ChanR ),
			        "RevE", CALCULATE( SUM( Fact[Sales Amount] ), Dim_channel[channel] = _ChanE ),
			        "RevD", CALCULATE( SUM( Fact[Sales Amount] ), Dim_channel[channel] = _ChanD )
			    )
			
			-- Max per channel (guard against all-blank)
			VAR _MaxR = IFERROR( MAXX( _Pivot, [RevR] ), 1 )
			VAR _MaxE = IFERROR( MAXX( _Pivot, [RevE] ), 1 )
			VAR _MaxD = IFERROR( MAXX( _Pivot, [RevD] ), 1 )
			
			-- Normalise to nearest 20% bucket
			VAR _PivotN =
			    ADDCOLUMNS(
			        _Pivot,
			        "NR", IF( [RevR] > 0 && _MaxR > 0, MROUND( [RevR] / _MaxR * 100, 20 ), 0 ),
			        "NE", IF( [RevE] > 0 && _MaxE > 0, MROUND( [RevE] / _MaxE * 100, 20 ), 0 ),
			        "ND", IF( [RevD] > 0 && _MaxD > 0, MROUND( [RevD] / _MaxD * 100, 20 ), 0 )
			    )
			
			-- Build table rows
			VAR _Rows =
			    CONCATENATEX(
			        _PivotN,
			
			        VAR _NR = [NR]
			        VAR _NE = [NE]
			        VAR _ND = [ND]
			
			        -- Badge background colours (teal scale matching dashboard theme)
			        VAR _BR =
			            SWITCH( TRUE(),
			                _NR >= 100, "#0B5E4B",
			                _NR >= 80,  "#1D9E75",
			                _NR >= 60,  "#5DCAA5",
			                _NR >= 40,  "#C9940A",
			                _NR >= 20,  "#E8E6DF",
			                            "#F4F3F0"
			            )
			        VAR _BE =
			            SWITCH( TRUE(),
			                _NE >= 100, "#0B5E4B",
			                _NE >= 80,  "#1D9E75",
			                _NE >= 60,  "#5DCAA5",
			                _NE >= 40,  "#C9940A",
			                _NE >= 20,  "#E8E6DF",
			                            "#F4F3F0"
			            )
			        VAR _BD =
			            SWITCH( TRUE(),
			                _ND >= 100, "#0B5E4B",
			                _ND >= 80,  "#1D9E75",
			                _ND >= 60,  "#5DCAA5",
			                _ND >= 40,  "#C9940A",
			                _ND >= 20,  "#E8E6DF",
			                            "#F4F3F0"
			            )
			
			        -- Badge text colours
			        VAR _TR = IF( _NR >= 60, "#ffffff", IF( _NR >= 40, "#1a1a1a", "#9ca3af" ) )
			        VAR _TE = IF( _NE >= 60, "#ffffff", IF( _NE >= 40, "#1a1a1a", "#9ca3af" ) )
			        VAR _TD = IF( _ND >= 60, "#ffffff", IF( _ND >= 40, "#1a1a1a", "#9ca3af" ) )
			
			        -- Badge labels
			        VAR _LR = IF( _NR = 0, UNICHAR(8212), FORMAT( _NR, "0" ) & "%" )
			        VAR _LE = IF( _NE = 0, UNICHAR(8212), FORMAT( _NE, "0" ) & "%" )
			        VAR _LD = IF( _ND = 0, UNICHAR(8212), FORMAT( _ND, "0" ) & "%" )
			
			        -- Reusable badge snippet (inline-block is the key fix — prevents full-width stretch)
			        VAR _Badge_R =
			            "<div style='display:inline-block;background:" & _BR & ";color:" & _TR
			            & ";border-radius:4px;padding:3px 10px;font-size:11px;font-weight:700;"
			            & "min-width:46px;text-align:center;'>" & _LR & "</div>"
			
			        VAR _Badge_E =
			            "<div style='display:inline-block;background:" & _BE & ";color:" & _TE
			            & ";border-radius:4px;padding:3px 10px;font-size:11px;font-weight:700;"
			            & "min-width:46px;text-align:center;'>" & _LE & "</div>"
			
			        VAR _Badge_D =
			            "<div style='display:inline-block;background:" & _BD & ";color:" & _TD
			            & ";border-radius:4px;padding:3px 10px;font-size:11px;font-weight:700;"
			            & "min-width:46px;text-align:center;'>" & _LD & "</div>"
			
			        RETURN
			            "<tr>"
			            & "<td class='sku-cell'>" & [Product_id] & "</td>"
			            & "<td class='val-cell'>" & _Badge_R & "</td>"
			            & "<td class='val-cell'>" & _Badge_E & "</td>"
			            & "<td class='val-cell'>" & _Badge_D & "</td>"
			            & "</tr>",
			
			        UNICHAR(10),
			        [TotalRev],
			        DESC
			    )
			
			-- Legend row (matches dashboard reference)
			VAR _Legend =
			    "<div class='legend'>"
			    & "<span class='dot' style='background:#0B5E4B'></span>Very High &nbsp;"
			    & "<span class='dot' style='background:#1D9E75'></span>High &nbsp;"
			    & "<span class='dot' style='background:#5DCAA5'></span>Med &nbsp;"
			    & "<span class='dot' style='background:#E8E6DF;border:1px solid #ccc'></span>Low &nbsp;"
			    & "<span class='dot' style='background:#F4F3F0;border:1px solid #ccc'></span>Minimal"
			    & "</div>"
			
			-- Full HTML document — this is what was missing before
			VAR _HTML =
			    "<!DOCTYPE html><html><head><meta charset='utf-8'><style>"
			
			    -- Reset & base
			    & "* { box-sizing:border-box; margin:0; padding:0; }"
			    & "body { font-family: 'Segoe UI', Arial, sans-serif; font-size:12px;"
			    &        "background:#fff; padding:10px; }"
			
			    -- Legend
			    & ".legend { display:flex; align-items:center; gap:4px; flex-wrap:wrap;"
			    &           "font-size:10px; color:#6b7280; margin-bottom:10px; }"
			    & ".dot { display:inline-block; width:10px; height:10px;"
			    &        "border-radius:2px; margin-right:3px; }"
			
			    -- Table structure
			    & "table { width:100%; border-collapse:collapse; }"
			
			    -- Header
			    & "thead th { padding:6px 8px; font-size:10px; font-weight:600;"
			    &            "color:#6b7280; text-transform:uppercase; letter-spacing:.04em;"
			    &            "border-bottom:2px solid #e5e7eb; background:#fafafa; }"
			    & "thead th:first-child { text-align:left; }"
			    & "thead th:not(:first-child) { text-align:center; }"
			
			    -- Body cells
			    & ".sku-cell { padding:6px 10px; font-size:11px; font-weight:600;"
			    &             "color:#374151; white-space:nowrap; }"
			    & ".val-cell { padding:5px 6px; text-align:center;"
			    &             "vertical-align:middle; }"
			
			    -- Row dividers and hover
			    & "tbody tr { border-bottom:1px solid #f0efec; }"
			    & "tbody tr:last-child { border-bottom:none; }"
			    & "tbody tr:hover { background:#f9fafb; }"
			
			    & "</style></head><body>"
			
			    -- Header
			    & "<div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:18px;'>"
			    & "<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222;text-transform:uppercase;'>SKU X Channel Performance</span>"
			    & "<span style='font-size:10px;color:#aaa;'>Revenue Contribution</span>"
			    & "</div>"
			
			    -- Legend below the header
			    & _Legend
			
			    -- Table
			    & "<table>"
			    & "<thead><tr>"
			    & "<th>SKU</th>"
			    & "<th>Retail</th>"
			    & "<th>E-Commerce</th>"
			    & "<th>Discount</th>"
			    & "</tr></thead>"
			    & "<tbody>" & _Rows & "</tbody>"
			    & "</table>"
			    & "</body></html>"
			
			RETURN _HTML
		lineageTag: d580f880-e87a-4ed7-b9f6-067a746d7d47

	measure HTML_RevenuePareto =
			
			
			-- ══ CONFIG ════════════════════════════════════════════════════════
			VAR _TopN      = 10       -- bars to show individually
			VAR _ParetoTgt = 0.80     -- 80% threshold
			VAR _SVGW      = 580
			VAR _SVGH      = 235
			VAR _ML        = 44       -- left margin (revenue axis)
			VAR _MR        = 38       -- right margin (cumulative % axis)
			VAR _MT        = 14
			VAR _MB        = 54       -- bottom margin for rotated labels
			VAR _CW        = _SVGW - _ML - _MR
			VAR _CH        = _SVGH - _MT - _MB
			
			-- ══ STEP A · ALL SKU REVENUE (filter out blanks) ═══════════════════
			VAR _AllSKU =
			    FILTER(
			        ADDCOLUMNS(
			            VALUES( Dim_Product[Product_id] ),
			            "Rev", CALCULATE( SUM( Fact[Sales Amount] ) )
			        ),
			        NOT ISBLANK( [Rev] ) && [Rev] > 0
			    )
			
			VAR _TotalRev   = SUMX( _AllSKU, [Rev] )
			VAR _TotalCount = COUNTROWS( _AllSKU )
			
			-- ══ STEP B · TOP N FOR CHART DISPLAY ══════════════════════════════
			VAR _TopSKUs = TOPN( _TopN, _AllSKU, [Rev], DESC )
			
			VAR _Ranked =
			    ADDCOLUMNS(
			        _TopSKUs,
			        "Rk", RANKX( _TopSKUs, [Rev],, DESC, Dense )
			    )
			
			-- Cumulative % for top N (for chart line)
			VAR _WithCumul =
			    ADDCOLUMNS(
			        _Ranked,
			        "CumPct",
			        VAR _R = [Rk]
			        RETURN
			            IF( _TotalRev > 0,
			                SUMX( FILTER( _Ranked, [Rk] <= _R ), [Rev] ) / _TotalRev,
			                0 )
			    )
			
			-- ══ STEP C · ALL-SKU CUMULATIVE for Pareto Count ══════════════════
			-- Separate from top-N so count is accurate even if 80% falls in Others
			VAR _AllRanked =
			    ADDCOLUMNS(
			        _AllSKU,
			        "Rk_All", RANKX( _AllSKU, [Rev],, DESC, Dense )
			    )
			
			VAR _AllCumul =
			    ADDCOLUMNS(
			        _AllRanked,
			        "CumRev",
			        VAR _R = [Rk_All]
			        RETURN SUMX( FILTER( _AllRanked, [Rk_All] <= _R ), [Rev] )
			    )
			
			VAR _ParetoSKUs =
			    MINX( FILTER( _AllCumul, [CumRev] >= _TotalRev * _ParetoTgt ), [Rk_All] )
			VAR _RemCount = _TotalCount - _ParetoSKUs
			
			-- ══ STEP D · OTHERS BUCKET ════════════════════════════════════════
			VAR _TopRev   = SUMX( _TopSKUs, [Rev] )
			VAR _OtherRev = _TotalRev - _TopRev
			
			-- ══ STEP E · BAR SCALE & GEOMETRY ════════════════════════════════
			VAR _MaxRev    = MAXX( _WithCumul, [Rev] )
			VAR _MaxRevScl = _MaxRev * 1.05     -- 5% headroom above tallest bar
			
			VAR _NItems  = _TopN + 1
			VAR _SlotW   = _CW / _NItems
			VAR _BarW    = _SlotW * 0.62
			VAR _BarGap  = ( _SlotW - _BarW ) / 2
			
			-- ══ STEP F · BARS (Top N) ════════════════════════════════════════
			VAR _Bars =
			    CONCATENATEX(
			        _WithCumul,
			        VAR _BX = _ML + ( [Rk] - 1 ) * _SlotW + _BarGap
			        VAR _BH = INT( ( [Rev] / _MaxRevScl ) * _CH )
			        VAR _BY = _MT + _CH - _BH
			        RETURN
			        "<rect x='"      & FORMAT( _BX,   "0.0" ) & "'
			               y='"      & FORMAT( _BY,   "0"   ) & "'
			               width='"  & FORMAT( _BarW, "0.0" ) & "'
			               height='" & FORMAT( _BH,   "0"   ) & "'
			               fill='#14532d' rx='2'/>",
			        "",
			        [Rk], ASC
			    )
			
			-- ══ STEP G · OTHERS BAR (lighter colour) ═════════════════════════
			VAR _OtherBX = _ML + _TopN * _SlotW + _BarGap
			VAR _OtherBH = INT( ( _OtherRev / _MaxRevScl ) * _CH )
			VAR _OtherBY = _MT + _CH - _OtherBH
			VAR _OtherBar =
			    "<rect x='"      & FORMAT( _OtherBX, "0.0" ) & "'
			           y='"      & FORMAT( _OtherBY, "0"   ) & "'
			           width='"  & FORMAT( _BarW,    "0.0" ) & "'
			           height='" & FORMAT( _OtherBH, "0"   ) & "'
			           fill='#a3c4a8' rx='2'/>"
			
			-- ══ STEP H · CUMULATIVE LINE + CIRCLES ════════════════════════════
			VAR _LinePoints =
			    CONCATENATEX(
			        _WithCumul,
			        FORMAT( _ML + ( [Rk] - 0.5 ) * _SlotW, "0.0" )
			        & "," &
			        FORMAT( _MT + _CH - ( [CumPct] * _CH ), "0.0" ),
			        " ",
			        [Rk], ASC
			    )
			
			-- Final point: Others at 100%
			VAR _OtherXC   = _ML + ( _TopN + 0.5 ) * _SlotW
			VAR _FullLine  = _LinePoints & " " & FORMAT( _OtherXC, "0.0" ) & "," & FORMAT( _MT, "0" )
			
			VAR _Circles =
			    CONCATENATEX(
			        _WithCumul,
			        VAR _CX = _ML + ( [Rk] - 0.5 ) * _SlotW
			        VAR _CY = _MT + _CH - ( [CumPct] * _CH )
			        RETURN
			        "<circle cx='" & FORMAT( _CX, "0.0" ) & "'
			                 cy='" & FORMAT( _CY, "0.0" ) & "'
			                 r='3' fill='#d97706' stroke='#fff' stroke-width='1.2'/>",
			        "",
			        [Rk], ASC
			    )
			
			VAR _OtherCircle =
			    "<circle cx='" & FORMAT( _OtherXC, "0.0" ) & "'
			             cy='" & FORMAT( _MT, "0" ) & "'
			             r='3' fill='#d97706' stroke='#fff' stroke-width='1.2'/>"
			
			-- ══ STEP I · X-AXIS LABELS (rotated -45°) ═════════════════════════
			VAR _XLabels =
			    CONCATENATEX(
			        _WithCumul,
			        VAR _XC  = _ML + ( [Rk] - 0.5 ) * _SlotW
			        VAR _YLb = _MT + _CH + 5
			        RETURN
			        "<text transform='rotate(-45 " & FORMAT( _XC, "0.0" ) & " " & FORMAT( _YLb, "0" ) & ")'
			               x='"         & FORMAT( _XC, "0.0" ) & "'
			               y='"         & FORMAT( _YLb, "0"  ) & "'
			               font-size='9' fill='#6b7280' text-anchor='end'>"
			        & [Product_id] & "</text>",
			        "",
			        [Rk], ASC
			    )
			
			VAR _OtherLblY = _MT + _CH + 5
			VAR _OtherXLabel =
			    "<text transform='rotate(-45 " & FORMAT( _OtherXC, "0.0" ) & " " & FORMAT( _OtherLblY, "0" ) & ")'
			           x='"         & FORMAT( _OtherXC,  "0.0" ) & "'
			           y='"         & FORMAT( _OtherLblY, "0"  ) & "'
			           font-size='9' fill='#6b7280' text-anchor='end'>Others</text>"
			
			-- ══ STEP J · LEFT Y-AXIS (Revenue) ════════════════════════════════
			VAR _MaxRevM = INT( _MaxRevScl / 1000000 ) + 1
			VAR _YStep   = IF( _MaxRevM <= 10, 2, IF( _MaxRevM <= 25, 5, 10 ) )
			
			VAR _LeftAxis =
			    CONCATENATEX(
			        FILTER(
			            ADDCOLUMNS(
			                GENERATESERIES( 0, 7, 1 ),
			                "VM", [Value] * _YStep,
			                "YP", _MT + _CH - ( [Value] * _YStep * 1000000 / _MaxRevScl ) * _CH
			            ),
			            [VM] * 1000000 <= _MaxRevScl
			        ),
			        "<text x='" & FORMAT( _ML - 4, "0"   ) & "'
			               y='" & FORMAT( [YP] + 3, "0.0" ) & "'
			               font-size='9' fill='#9ca3af' text-anchor='end'>"
			        & FORMAT( [VM], "0" ) & "M</text>"
			        & "<line x1='" & FORMAT( _ML,       "0"   ) & "' y1='" & FORMAT( [YP], "0.0" ) & "'
			                x2='" & FORMAT( _ML + _CW,  "0"   ) & "' y2='" & FORMAT( [YP], "0.0" ) & "'
			                stroke='#f3f4f6' stroke-width='1'/>",
			        "",
			        [Value], ASC
			    )
			
			-- ══ STEP K · RIGHT Y-AXIS (Cumulative %) ══════════════════════════
			VAR _RightAxis =
			    CONCATENATEX(
			        ADDCOLUMNS( GENERATESERIES( 0, 5, 1 ), "Pct", [Value] * 20 ),
			        VAR _YR = _MT + _CH - ( [Pct] / 100 ) * _CH
			        RETURN
			        "<text x='" & FORMAT( _ML + _CW + 4, "0"   ) & "'
			               y='" & FORMAT( _YR + 3,        "0.0" ) & "'
			               font-size='9' fill='#d97706' text-anchor='start'>"
			        & FORMAT( [Pct], "0" ) & "%</text>",
			        "",
			        [Value], ASC
			    )
			
			-- ══ STEP L · 80% THRESHOLD LINE ═══════════════════════════════════
			VAR _80Y =  _MT + _CH - ( 0.80 * _CH )
			VAR _ThreshLine =
			    "<line x1='" & FORMAT( _ML,      "0"   ) & "' y1='" & FORMAT( _80Y, "0.0" ) & "'
			           x2='" & FORMAT( _ML + _CW,"0"   ) & "' y2='" & FORMAT( _80Y, "0.0" ) & "'
			           stroke='#ef4444' stroke-width='1.5' stroke-dasharray='5,3' opacity='0.8'/>"
			  & "<text x='" & FORMAT( _ML + _CW - 2, "0"   ) & "'
			           y='" & FORMAT( _80Y - 4,        "0.0" ) & "'
			           font-size='9' font-weight='600' fill='#ef4444' text-anchor='end'>80%</text>"
			
			-- ══ STEP M · FOOTER ═══════════════════════════════════════════════
			VAR _FooterTxt =
			    "Top " & FORMAT( _ParetoSKUs, "0" ) & " SKUs generate 80% of revenue — remaining "
			    & FORMAT( _RemCount, "0" ) & " SKUs contribute only 20%, signalling portfolio rationalisation opportunity"
			
			-- ══ ASSEMBLE ══════════════════════════════════════════════════════
			RETURN
			"<div style='font-family:Segoe UI,sans-serif;padding:12px 14px;
			             background:#fff;border-radius:6px;box-sizing:border-box;'>
			
			  <div style='display:flex;justify-content:space-between;
			              align-items:baseline;margin-bottom:8px;'>
			    <span style='font-size:11px;font-weight:700;
			                 letter-spacing:.07em;color:#1a1a1a;'>
			      Revenue Pareto · Top SKUs
			    </span>
			    <span style='font-size:10px;color:#aaa;'>Cumulative % revenue — AED</span>
			  </div>
			
			  <svg width='100%'
			       viewBox='0 0 " & FORMAT( _SVGW, "0" ) & " " & FORMAT( _SVGH, "0" ) & "'
			       xmlns='http://www.w3.org/2000/svg'>
			
			    " & _LeftAxis & "
			    " & _Bars & "
			    " & _OtherBar & "
			
			    <polyline points='" & _FullLine & "'
			      fill='none' stroke='#d97706' stroke-width='2'/>
			
			    " & _Circles & "
			    " & _OtherCircle & "
			    " & _ThreshLine & "
			    " & _RightAxis & "
			
			    <line x1='" & FORMAT( _ML,      "0" ) & "' y1='" & FORMAT( _MT + _CH, "0" ) & "'
			          x2='" & FORMAT( _ML + _CW,"0" ) & "' y2='" & FORMAT( _MT + _CH, "0" ) & "'
			          stroke='#e5e7eb' stroke-width='1'/>
			
			    " & _XLabels & "
			    " & _OtherXLabel & "
			
			  </svg>
			
			  <div style='margin-top:4px;padding:5px 10px;background:#fef2f2;
			              border-left:3px solid #ef4444;font-size:10px;color:#555;
			              border-radius:0 3px 3px 0;'>
			    ✦ " & _FooterTxt & "
			  </div>
			</div>"
		lineageTag: aafca3c7-cf80-44d4-8a2c-24b64d742d66

	measure KPI_ActiveSKUs =
			
			
			VAR _CY = MAXX( ALL( Dim_Date ), Dim_Date[year] )
			
			-- Active SKUs: distinct products with any sales (all time)
			VAR _ActiveCount =
			    COUNTROWS(
			        FILTER(
			            VALUES( Dim_Product[Product_id] ),
			            CALCULATE( SUM( Fact[Sales Amount] ) ) > 0
			        )
			    )
			
			-- Total SKUs in master list
			VAR _TotalCount = DISTINCTCOUNT( Dim_Product[Product_id] )
			
			-- New launches: in current year but absent in previous year
			VAR _CYSKUs =
			    CALCULATETABLE( VALUES( Dim_Product[Product_id] ), Dim_Date[year] = _CY )
			VAR _PYSKUs =
			    CALCULATETABLE( VALUES( Dim_Product[Product_id] ), Dim_Date[year] = _CY - 1 )
			VAR _NewLaunches = COUNTROWS( EXCEPT( _CYSKUs, _PYSKUs ) )
			
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			background:#FFFFFF;
			border-top:3px solid #2F5F8F;
			border-radius:10px;
			padding:16px 18px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='font-size:10px;font-weight:700;letter-spacing:1px;
			color:#67726C;text-transform:uppercase;margin-bottom:8px;'>
			ACTIVE SKUs
			</div>
			
			<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>
			" & FORMAT( _ActiveCount, "0" ) & "
			<span style='font-size:16px;font-weight:500;color:#67726C;'>
			/ " & FORMAT( _TotalCount, "0" ) & "
			</span>
			</div>
			
			<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>
			active vs total product universe
			</div>
			
			<div style='display:inline-block;font-size:11px;font-weight:600;
			padding:3px 9px;border-radius:6px;
			background:#E7F2EB;color:#2C5C3C;'>
			▲ " & FORMAT( _NewLaunches, "0" ) & " new launches
			</div>
			</div>"
		lineageTag: a3ca5c61-b33a-4c47-a28e-dd03f7a1a25d

	measure KPI_ParetoThreshold =
			
			
			-- Always shows all-time figure regardless of slicers
			VAR _AllSKU =
			    FILTER(
			        ADDCOLUMNS(
			            VALUES( Dim_Product[Product_id] ),
			            "Rev", CALCULATE(
			                SUM( Fact[Sales Amount] ),
			                REMOVEFILTERS( Dim_Date ),
			                REMOVEFILTERS( Dim_region )
			            )
			        ),
			        NOT ISBLANK( [Rev] ) && [Rev] > 0
			    )
			
			VAR _TotalRev   = SUMX( _AllSKU, [Rev] )
			VAR _TotalCount = COUNTROWS( _AllSKU )
			
			VAR _AllRanked =
			    ADDCOLUMNS(
			        _AllSKU,
			        "Rk", RANKX( _AllSKU, [Rev],, DESC, Dense )
			    )
			
			VAR _AllCumul =
			    ADDCOLUMNS(
			        _AllRanked,
			        "CumRev",
			        VAR _R = [Rk]
			        RETURN SUMX( FILTER( _AllRanked, [Rk] <= _R ), [Rev] )
			    )
			
			VAR _ParetoN  = MINX( FILTER( _AllCumul, [CumRev] >= _TotalRev * 0.80 ), [Rk] )
			VAR _RestCount = _TotalCount - _ParetoN
			VAR _RestPct  = FORMAT( _RestCount / _TotalCount * 100, "0" ) & "%"
			
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			background:#FFFFFF;
			border-top:3px solid #2F5F8F;
			border-radius:10px;
			padding:16px 18px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='font-size:10px;font-weight:700;letter-spacing:1px;
			color:#67726C;text-transform:uppercase;margin-bottom:8px;'>
			PARETO THRESHOLD
			</div>
			
			<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>
			" & FORMAT( _ParetoN, "0" ) & "
			<span style='font-size:18px;font-weight:600;'> SKUs</span>
			</div>
			
			<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>
			drive 80% of total portfolio revenue
			</div>
			
			<div style='display:inline-block;font-size:11px;font-weight:600;
			padding:3px 9px;border-radius:6px;
			background:#f3f4f6;color:#374151;'>
			80% of revenue
			</div>
			</div>"
		lineageTag: ad7275ff-871d-4449-8b8a-d007daa814d9

	measure KPI_RevenueGrowthMoM =
			
			
			-- Latest month with actual sales
			VAR _LastDate =
			    MAXX(
			        FILTER(
			            ALL(Fact),
			            NOT ISBLANK(Fact[Sales Amount])
			        ),
			        Fact[date]
			    )
			
			VAR _CY = YEAR(_LastDate)
			VAR _CM = MONTH(_LastDate)
			
			VAR _PM = IF(_CM = 1, 12, _CM - 1)
			VAR _PY = IF(_CM = 1, _CY - 1, _CY)
			
			VAR _CurRev =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[year] = _CY
			                && Dim_Date[month] = _CM
			        )
			    )
			
			VAR _PrevRev =
			    CALCULATE(
			        SUM(Fact[Sales Amount]),
			        FILTER(
			            ALL(Dim_Date),
			            Dim_Date[year] = _PY
			                && Dim_Date[month] = _PM
			        )
			    )
			
			VAR _Effect = _CurRev - _PrevRev
			VAR _EffectM = DIVIDE(_Effect, 1000000)
			
			VAR _GrowthPct =
			    DIVIDE(_Effect, _PrevRev)
			
			VAR _Color =
			    IF(_Effect >= 0, "#2C5C3C", "#C27C00")
			
			VAR _Bg =
			    IF(_Effect >= 0, "#E7F2EB", "#F7E8B5")
			
			VAR _Arrow =
			    IF(_Effect >= 0, "↑", "↓")
			
			VAR _Sign =
			    IF(_Effect >= 0, "+", "-")
			
			VAR _MonthName =
			    SWITCH(
			        _CM,
			        1,"Jan",2,"Feb",3,"Mar",4,"Apr",
			        5,"May",6,"Jun",7,"Jul",8,"Aug",
			        9,"Sep",10,"Oct",11,"Nov",12,"Dec"
			    )
			
			VAR _PrevMonthName =
			    SWITCH(
			        _PM,
			        1,"Jan",2,"Feb",3,"Mar",4,"Apr",
			        5,"May",6,"Jun",7,"Jul",8,"Aug",
			        9,"Sep",10,"Oct",11,"Nov",12,"Dec"
			    )
			
			RETURN
			
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			background:#FFFFFF;
			border-top:3px solid #2F5F8F;
			border-radius:10px;
			padding:16px 18px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='font-size:10px;font-weight:700;letter-spacing:1px;
			color:#67726C;text-transform:uppercase;margin-bottom:8px;'>
			REVENUE GROWTH MOM
			</div>
			
			<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>
			" & _Sign & FORMAT(ABS(_EffectM), "0.0") & "M
			</div>
			
			<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>
			revenue change " & _PrevMonthName & " → " & _MonthName & " " & FORMAT(_CY,"0") & "
			</div>
			
			<div style='display:inline-block;font-size:11px;font-weight:600;
			padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>
			" & _Arrow & " " & FORMAT(ABS(_GrowthPct),"0.0%") & " vs last month
			</div>
			
			</div>"
		lineageTag: f4c1854b-f011-4322-a233-bb2df773cb7f

	measure 'Avg Visibility Score' =
			
			DIVIDE(
			    SUM( Fact[stock_available] ),
			    SUM( Fact[stock_available] ) + SUM( Fact[units_sold] )
			)
		lineageTag: e5bb8503-d7a0-477a-9e0c-bf29f931ce95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure KPI_AvgVisibilityScore =
			
			
			VAR _Score  = [Avg Visibility Score]
			VAR _Target = 0.07          -- adjust to your actual target
			
			VAR _Diff   = _Score - _Target
			VAR _Color  = IF( _Diff >= 0, "#2C5C3C", "#C27C00" )
			VAR _Bg     = IF( _Diff >= 0, "#E7F2EB", "#F7E8B5" )
			VAR _Arrow  = IF( _Diff >= 0, "▲", "▼" )
			VAR _Sign   = IF( _Diff >= 0, "+", "" )   -- negative already has minus sign
			
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;
			background:#FFFFFF;
			border-top:3px solid #2F5F8F;
			border-radius:10px;
			padding:16px 18px;
			height:90%;
			box-sizing:border-box;'>
			
			<div style='font-size:10px;font-weight:700;letter-spacing:1px;
			color:#67726C;text-transform:uppercase;margin-bottom:8px;'>
			AVG VISIBILITY SCORE
			</div>
			
			<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>
			" & FORMAT( _Score, "0.000" ) & "
			</div>
			
			<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>
			avg shelf fill rate, all outlet types
			</div>
			
			<div style='display:inline-block;font-size:11px;font-weight:600;
			padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>
			" & _Arrow & " " & _Sign & FORMAT( _Diff, "0.000" ) & " VS TARGET " & FORMAT( _Target, "0.000" ) & "
			</div>
			</div>"
		lineageTag: c8006932-3600-44c1-a2f0-183df45f813e

	measure HTML_ItemVisibilityByOutlet =
			
			
			-- ══ CONFIG ════════════════════════════════════════════════════
			VAR _Target   = 0.07      -- dashed target line
			VAR _MaxScale = 0.12      -- x-axis ceiling (gives breathing room)
			VAR _BarMaxW  = 380       -- max bar pixel width
			VAR _BarH     = 18        -- bar height
			VAR _LabelW   = 105       -- left label column width
			VAR _RowGap   = 30        -- vertical spacing between rows
			VAR _ValColW  = 44        -- right-side score label column
			
			VAR _SVGW = _LabelW + _BarMaxW + _ValColW + 10
			
			-- ══ STEP A · SCORE PER OUTLET TYPE ═══════════════════════════
			-- Dim_outlet[channel] holds outlet types (Hypermarket, Supermarket etc.)
			-- CALCULATE filters Fact rows through the Dim_outlet relationship
			VAR _Data =
			    ADDCOLUMNS(
			        FILTER(
			            VALUES( Dim_outlet[channel] ),
			            NOT ISBLANK( Dim_outlet[channel] )
			        ),
			        "Score",
			        CALCULATE(
			            DIVIDE(
			                SUM( Fact[stock_available] ),
			                SUM( Fact[stock_available] ) + SUM( Fact[units_sold] )
			            )
			        )
			    )
			
			-- Remove outlet types with no data
			VAR _DataClean = FILTER( _Data, NOT ISBLANK( [Score] ) && [Score] > 0 )
			
			-- ══ STEP B · RANK WORST → BEST (worst at top, best at bottom) ═══
			-- Row 1 (y=top) = worst performer so it reads like the screenshot
			VAR _Ranked =
			    ADDCOLUMNS(
			        _DataClean,
			        "Rk", RANKX( _DataClean, [Score],, ASC, Dense )
			    )
			
			VAR _NumRows = COUNTROWS( _DataClean )
			VAR _SVGH    = _NumRows * _RowGap + 32
			
			-- ══ STEP C · ENRICH: positions, colors, labels ════════════════
			VAR _Enriched =
			    ADDCOLUMNS(
			        _Ranked,
			        "RowY",  ( [Rk] - 1 ) * _RowGap + 4,
			        "TextY", ( [Rk] - 1 ) * _RowGap + 4 + _BarH - 5,
			        "BarW",  DIVIDE( [Score], _MaxScale ) * _BarMaxW,
			
			        -- RAG: green if at/above target, amber if within 30% below, red otherwise
			        "Color",
			        IF( [Score] >= _Target,              "#166534",
			        IF( [Score] >= _Target * 0.70,       "#ca8a04",
			                                             "#dc2626" ) )
			    )
			
			-- ══ STEP D · BUILD BAR ROWS ════════════════════════════════════
			VAR _Bars =
			    CONCATENATEX(
			        _Enriched,
			
			        -- Outlet type label (left side)
			        "<text x='0'
			               y='" & FORMAT( [TextY], "0" ) & "'
			               font-size='10' font-weight='600'
			               fill='#374151'>" & [channel] & "</text>"
			
			        -- Background track
			        & "<rect x='" & FORMAT( _LabelW, "0" ) & "'
			                y='" & FORMAT( [RowY],   "0" ) & "'
			                width='" & FORMAT( _BarMaxW, "0" ) & "'
			                height='" & FORMAT( _BarH, "0" ) & "'
			                fill='#f3f4f6' rx='3'/>"
			
			        -- Coloured bar
			        & "<rect x='" & FORMAT( _LabelW, "0" ) & "'
			                y='" & FORMAT( [RowY],   "0" ) & "'
			                width='" & FORMAT( [BarW], "0.1" ) & "'
			                height='" & FORMAT( _BarH,   "0" ) & "'
			                fill='" & [Color] & "' rx='3'/>"
			
			        -- Score value to right of bar
			        & "<text x='" & FORMAT( _LabelW + _BarMaxW + 6, "0" ) & "'
			                y='" & FORMAT( [TextY], "0" ) & "'
			                font-size='10' font-weight='600'
			                fill='#374151'>" & FORMAT( [Score], "0.000" ) & "</text>",
			
			        "",
			        [Rk], ASC      -- worst (rank 1) at top
			    )
			
			-- ══ STEP E · X-AXIS LABELS ════════════════════════════════════
			-- 0.00, 0.02, 0.04, 0.06, 0.08, 0.10 (every 0.02)
			VAR _XAxis =
			    CONCATENATEX(
			        ADDCOLUMNS(
			            GENERATESERIES( 0, 6, 1 ),
			            "XV",  [Value] * 0.02,
			            "XP",  _LabelW + DIVIDE( [Value] * 0.02, _MaxScale ) * _BarMaxW
			        ),
			        "<text x='"  & FORMAT( [XP], "0.0" ) & "'
			               y='"  & FORMAT( _SVGH - 4, "0" ) & "'
			               text-anchor='middle'
			               font-size='9' fill='#9ca3af'>"
			        & FORMAT( [XV], "0.00" ) & "</text>",
			        "",
			        [Value], ASC
			    )
			
			-- ══ STEP F · TARGET DASHED LINE ════════════════════════════════
			VAR _TargetX =
			    FORMAT( _LabelW + DIVIDE( _Target, _MaxScale ) * _BarMaxW, "0.1" )
			
			VAR _TargetLine =
			    "<line x1='" & _TargetX & "' y1='0'
			           x2='" & _TargetX & "' y2='" & FORMAT( _SVGH - 16, "0" ) & "'
			           stroke='#9ca3af' stroke-width='1.5' stroke-dasharray='4,3'/>"
			  & "<text x='" & _TargetX & "'
			           y='8'
			           text-anchor='middle'
			           font-size='9' fill='#9ca3af'>target</text>"
			
			-- ══ STEP G · DYNAMIC FOOTER ════════════════════════════════════
			-- Compares worst outlet vs best outlet scores dynamically
			VAR _BestOutlet  = MINX( FILTER( _Enriched, [Score] = MAXX( _Enriched, [Score] ) ), [channel] )
			VAR _WorstOutlet = MINX( FILTER( _Enriched, [Score] = MINX( _Enriched, [Score] ) ), [channel] )
			VAR _BestScore   = MAXX( _Enriched, [Score] )
			VAR _WorstScore  = MINX( _Enriched, [Score] )
			VAR _Ratio       = FORMAT( DIVIDE( _BestScore, _WorstScore ), "0.0" )
			
			VAR _FooterTxt =
			    _WorstOutlet & " visibility (" & FORMAT( _WorstScore, "0.000" ) & ") is "
			    & _Ratio & "× below " & _BestOutlet
			    & " — planogram compliance action required"
			
			-- ══ ASSEMBLE ══════════════════════════════════════════════════
			RETURN
			"<div style='font-family:Segoe UI,sans-serif;padding:12px 14px;
			             background:#fff;border-radius:6px;box-sizing:border-box;'>
			
			  <!-- HEADER -->
			  <div style='display:flex;justify-content:space-between;
			              align-items:baseline;margin-bottom:10px;'>
			    <span style='font-size:11px;font-weight:700;
			                 letter-spacing:.07em;color:#1a1a1a;'>
			      ITEM VISIBILITY SCORE · BY OUTLET TYPE
			    </span>
			    <span style='font-size:10px;color:#aaa;'>Avg shelf fill rate</span>
			  </div>
			
			  <!-- CHART -->
			  <svg width='100%'
			       viewBox='0 0 " & FORMAT( _SVGW, "0" ) & " " & FORMAT( _SVGH, "0" ) & "'
			       xmlns='http://www.w3.org/2000/svg'>
			
			    " & _Bars & "
			    " & _TargetLine & "
			    " & _XAxis & "
			
			    <!-- X-axis baseline -->
			    <line x1='" & FORMAT( _LabelW, "0" ) & "'
			          y1='" & FORMAT( _SVGH - 16, "0" ) & "'
			          x2='" & FORMAT( _LabelW + _BarMaxW, "0" ) & "'
			          y2='" & FORMAT( _SVGH - 16, "0" ) & "'
			          stroke='#e5e7eb' stroke-width='1'/>
			
			  </svg>
			
			  <!-- FOOTER CALLOUT -->
			  <div style='margin-top:4px;padding:5px 10px;background:#fef2f2;
			              border-left:3px solid #dc2626;font-size:10px;color:#555;
			              border-radius:0 3px 3px 0;'>
			    ✦ " & _FooterTxt & "
			  </div>
			</div>"
		lineageTag: d794da79-c2d9-4c03-8f18-52b6a4fa7816

	measure HTML_RevenueBridge = ```
			
			
			VAR OctRevenue = 8.2
			VAR Volume     = 0.8
			VAR Price      = 0.8
			VAR Mix        = -0.2
			VAR Promo      = -0.2
			
			VAR NovRevenue = OctRevenue + Volume + Price + Mix + Promo
			
			-- Running totals
			VAR Run1 = OctRevenue
			VAR Run2 = Run1 + Volume
			VAR Run3 = Run2 + Price
			VAR Run4 = Run3 + Mix
			VAR Run5 = Run4 + Promo
			
			-- Chart setup
			VAR YMin = 7.5
			VAR YMax = 10.5
			
			VAR ChartHeight = 260
			VAR ChartWidth  = 620
			
			VAR Scale =
			DIVIDE( ChartHeight , YMax - YMin )
			
			-- X Positions
			VAR X1 = 55
			VAR X2 = 150
			VAR X3 = 245
			VAR X4 = 340
			VAR X5 = 435
			VAR X6 = 530
			
			VAR BarWidth = 44
			
			-- Colors
			VAR TotalColor = "#2F6FAE"
			VAR Positive   = "#0E7C66"
			VAR Negative   = "#D9534F"
			VAR Connector  = "#D1D5DB"
			
			-- Heights
			VAR H_Oct =
			( OctRevenue - YMin ) * Scale
			
			VAR H_Vol =
			ABS( Volume ) * Scale
			
			VAR H_Price =
			ABS( Price ) * Scale
			
			VAR H_Mix =
			ABS( Mix ) * Scale
			
			VAR H_Promo =
			ABS( Promo ) * Scale
			
			VAR H_Nov =
			( NovRevenue - YMin ) * Scale
			
			-- Y coordinates
			VAR Y_Oct =
			ChartHeight - H_Oct
			
			VAR Y_Vol =
			ChartHeight - MAX( Run1 , Run2 ) * Scale + YMin * Scale
			
			VAR Y_Price =
			ChartHeight - MAX( Run2 , Run3 ) * Scale + YMin * Scale
			
			VAR Y_Mix =
			ChartHeight - MAX( Run3 , Run4 ) * Scale + YMin * Scale
			
			VAR Y_Promo =
			ChartHeight - MAX( Run4 , Run5 ) * Scale + YMin * Scale
			
			VAR Y_Nov =
			ChartHeight - H_Nov
			
			VAR FooterText =
			"Revenue increased from "
			& FORMAT( OctRevenue , "$0.0M" )
			& " to "
			& FORMAT( NovRevenue , "$0.0M" )
			& " driven primarily by Volume (+"
			& FORMAT( Volume , "0.0" )
			& "M) and Price (+"
			& FORMAT( Price , "0.0" )
			& "M)."
			
			RETURN
			
			"<div style='font-family:Segoe UI,sans-serif;
			          padding:12px 14px;
			          background:#fff;
			          border-radius:6px;'>
			
			<div style='display:flex;
			            justify-content:space-between;
			            margin-bottom:10px;'>
			
			<span style='font-size:11px;
			          font-weight:700;
			          letter-spacing:.07em;
			          color:#1a1a1a;'>
			REVENUE BRIDGE · OCT → NOV </span>
			
			<span style='font-size:10px;
			          color:#9ca3af;'>
			Impact Analysis ($M) </span>
			
			</div>
			
			<svg viewBox='0 0 620 300'
			  width='100%'
			  xmlns='http://www.w3.org/2000/svg'>
			
			<!-- CONNECTORS -->
			
			<line x1='" & (X1+22) & "'
			   y1='" & Y_Oct & "'
			   x2='" & X2 & "'
			   y2='" & Y_Oct & "'
			   stroke='" & Connector & "'
			   stroke-width='2'/>
			
			<line x1='" & (X2+22) & "'
			   y1='" & (ChartHeight-(Run2-YMin)*Scale) & "'
			   x2='" & X3 & "'
			   y2='" & (ChartHeight-(Run2-YMin)*Scale) & "'
			   stroke='" & Connector & "'
			   stroke-width='2'/>
			
			<line x1='" & (X3+22) & "'
			   y1='" & (ChartHeight-(Run3-YMin)*Scale) & "'
			   x2='" & X4 & "'
			   y2='" & (ChartHeight-(Run3-YMin)*Scale) & "'
			   stroke='" & Connector & "'
			   stroke-width='2'/>
			
			<line x1='" & (X4+22) & "'
			   y1='" & (ChartHeight-(Run4-YMin)*Scale) & "'
			   x2='" & X5 & "'
			   y2='" & (ChartHeight-(Run4-YMin)*Scale) & "'
			   stroke='" & Connector & "'
			   stroke-width='2'/>
			
			<line x1='" & (X5+22) & "'
			   y1='" & (ChartHeight-(Run5-YMin)*Scale) & "'
			   x2='" & X6 & "'
			   y2='" & (ChartHeight-(Run5-YMin)*Scale) & "'
			   stroke='" & Connector & "'
			   stroke-width='2'/>
			
			<!-- OCT TOTAL -->
			
			<rect x='" & X1 & "'
			   y='" & Y_Oct & "'
			   width='" & BarWidth & "'
			   height='" & H_Oct & "'
			   fill='" & TotalColor & "'
			   rx='4'/>
			
			<!-- VOLUME -->
			
			<rect x='" & X2 & "'
			   y='" & Y_Vol & "'
			   width='" & BarWidth & "'
			   height='" & H_Vol & "'
			   fill='" & Positive & "'
			   rx='4'/>
			
			<!-- PRICE -->
			
			<rect x='" & X3 & "'
			   y='" & Y_Price & "'
			   width='" & BarWidth & "'
			   height='" & H_Price & "'
			   fill='" & Positive & "'
			   rx='4'/>
			
			<!-- MIX -->
			
			<rect x='" & X4 & "'
			   y='" & Y_Mix & "'
			   width='" & BarWidth & "'
			   height='" & H_Mix & "'
			   fill='" & Negative & "'
			   rx='4'/>
			
			<!-- PROMO -->
			
			<rect x='" & X5 & "'
			   y='" & Y_Promo & "'
			   width='" & BarWidth & "'
			   height='" & H_Promo & "'
			   fill='" & Negative & "'
			   rx='4'/>
			
			<!-- NOV TOTAL -->
			
			<rect x='" & X6 & "'
			   y='" & Y_Nov & "'
			   width='" & BarWidth & "'
			   height='" & H_Nov & "'
			   fill='" & TotalColor & "'
			   rx='4'/>
			
			<!-- VALUES -->
			
			<text x='" & (X1+22) & "' y='" & (Y_Oct-8) & "'
			   text-anchor='middle'
			   font-size='10'
			   font-weight='600'>
			" & FORMAT(OctRevenue,"0.0") & " </text>
			
			<text x='" & (X6+22) & "' y='" & (Y_Nov-8) & "'
			   text-anchor='middle'
			   font-size='10'
			   font-weight='600'>
			" & FORMAT(NovRevenue,"0.0") & " </text>
			
			<!-- CATEGORY LABELS -->
			
			<text x='" & (X1+22) & "' y='285' text-anchor='middle' font-size='10'>Oct</text> <text x='" & (X2+22) & "' y='285' text-anchor='middle' font-size='10'>Volume</text> <text x='" & (X3+22) & "' y='285' text-anchor='middle' font-size='10'>Price</text> <text x='" & (X4+22) & "' y='285' text-anchor='middle' font-size='10'>Mix</text> <text x='" & (X5+22) & "' y='285' text-anchor='middle' font-size='10'>Promo</text> <text x='" & (X6+22) & "' y='285' text-anchor='middle' font-size='10'>Nov</text>
			
			</svg>
			
			<div style='margin-top:4px;
			            padding:5px 10px;
			            background:#eff6ff;
			            border-left:3px solid #2563eb;
			            font-size:10px;
			            color:#555;
			            border-radius:0 3px 3px 0;'>
			
			✦ " & FooterText & "
			
			</div>
			
			</div>"
			
			```
		lineageTag: 5f316d46-c14f-4d84-a3b6-b0bf12fe77ae

	measure 'Avg Units Sold' = AVERAGE(Fact[units_sold])
		lineageTag: 20f0b06d-b6d6-489b-9ff2-a995d6865987

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Baseline Sales' = ```
			CALCULATE([Avg Units Sold], Fact[promotion_flag] = 0)
			
			```
		lineageTag: a86895ee-d85b-4b2c-ad93-47d272530b01

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promoted Sales' = ```
			CALCULATE([Avg Units Sold], Fact[promotion_flag] = 1)
			
			```
		lineageTag: 2b9b6273-5dab-41ad-92f8-febac59cfe5f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promo Lift %' = ```
			DIVIDE([Promoted Sales] - [Baseline Sales], [Baseline Sales])
			
			
			```
		lineageTag: 260bc637-5b27-4d40-94a9-5cccf4674759

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promo Frequency %' = ```
			
			DIVIDE(
			    CALCULATE(COUNTROWS('Fact'), Fact[promotion_flag] = 1),
			    COUNTROWS('Fact')
			)
			
			
			```
		lineageTag: 256f7ccd-066c-4919-8bfe-6c8966ccf12b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overall Promo ROI' = ```
			
			VAR PromotedTotal = CALCULATE([Avg Units Sold], Fact[promotion_flag] = 1, ALLSELECTED())
			VAR BaselineTotal = CALCULATE([Avg Units Sold], Fact[promotion_flag] = 0, ALLSELECTED())
			RETURN DIVIDE(PromotedTotal, BaselineTotal)
			
			
			```
		lineageTag: 5c725812-da05-4a76-b7ba-da6cb4ada852

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue at Risk SKUs' =
			
			COUNTROWS(
			    FILTER(VALUES(Dim_Product[sku]), CALCULATE([Promo Lift %]) < 0.05)
			)
		formatString: 0
		lineageTag: 53e368fb-4d3a-47d1-9fe3-7cbbfe13b8f1

	measure 'Promo Bar Chart Card' =
			
			VAR ChartH = 42
			VAR BarW = 14
			VAR BarGap = 2
			VAR GroupW = 55
			VAR StartX = 15
			VAR Categories = VALUES(Dim_Product[category])
			VAR MaxVal =
			    MAXX(
			        Categories,
			        MAX(CALCULATE([Baseline Sales]), CALCULATE([Promoted Sales]))
			    )
			VAR Bars =
			    CONCATENATEX(
			        Categories,
			        VAR CatRank = RANKX(ALL(Dim_Product[category]), Dim_Product[category], , ASC, Dense) - 1
			        VAR XPos = StartX + CatRank * GroupW
			        VAR Baseline = CALCULATE([Baseline Sales])
			        VAR Promoted = CALCULATE([Promoted Sales])
			        VAR BaseH = DIVIDE(Baseline, MaxVal) * ChartH
			        VAR PromH = DIVIDE(Promoted, MaxVal) * ChartH
			        RETURN
			        "<rect x='" & XPos & "' y='" & FORMAT(100 - BaseH, "0.0") & "' width='" & BarW & "' height='" & FORMAT(BaseH, "0.0") & "' fill='#cfe4d6'/>" &
			        "<rect x='" & (XPos + BarW + BarGap) & "' y='" & FORMAT(100 - PromH, "0.0") & "' width='" & BarW & "' height='" & FORMAT(PromH, "0.0") & "' fill='#1f6b45'/>" &
			        "<text x='" & (XPos + BarW) & "' y='112' text-anchor='middle' font-size='8' fill='#3f7a53'>" & Dim_Product[category] & "</text>",
			        "",
			        RANKX(ALL(Dim_Product[category]), Dim_Product[category], , ASC, Dense), ASC
			    )
			VAR WeakestCat =
			    MINX(
			        TOPN(1, Categories, CALCULATE([Promo Lift %]), ASC),
			        Dim_Product[category]
			    )
			VAR WeakestLift = CALCULATE([Promo Lift %], Dim_Product[category] = WeakestCat)
			VAR InsightText =
			    WeakestCat & " category shows the weakest incremental lift at " &
			    FORMAT(WeakestLift, "0.0%") &
			    " — promoted volume barely clears baseline, signalling promo fatigue."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:14px;font-family:sans-serif'>" &
			"<div style='font-size:12px;font-weight:600;color:#1a1a1a;margin-bottom:2px'>Baseline vs promoted units &middot; by category</div>" &
			"<div style='font-size:10px;color:#9a9a92;margin-bottom:10px'>Avg units sold</div>" &
			"<svg viewBox='0 0 300 105' xmlns='http://www.w3.org/2000/svg'>"  &
			Bars &
			"<g transform='translate(245,8)'>" &
			"<rect width='6' height='6' fill='#cfe4d6'/><text x='9' y='6' font-size='6.5' fill='#3f7a53'>baseline</text>" &
			"<rect y='11' width='6' height='6' fill='#1f6b45'/><text x='9' y='17' font-size='6.5' fill='#1f6b45'>promoted</text>" &
			"</g></svg>" &
			"<div style='background:#fbe4e4;border-radius:4px;padding:8px 10px;margin-top:4px;font-size:10.5px;color:#8a2f2f;line-height:1.5'>&#10022; " &
			InsightText &
			"</div>" &
			"</div>"
		lineageTag: 9a0aaf00-5f21-4eb8-adeb-be082d09e244

	measure 'Promo Scatter Card' =
			
			VAR PlotW = 260
			VAR PlotH = 82
			VAR OriginX = 30
			VAR OriginY = 8
			VAR SKUs = VALUES(Dim_Product[sku])
			VAR LiftThreshold = 0.05
			VAR FreqThreshold =
			    PERCENTILEX.INC(SKUs, CALCULATE([Promo Frequency %]), 0.5)
			VAR MinFreq = MINX(SKUs, CALCULATE([Promo Frequency %]))
			VAR MaxFreq = MAXX(SKUs, CALCULATE([Promo Frequency %]))
			VAR MinLift = MINX(SKUs, CALCULATE([Promo Lift %]))
			VAR MaxLift = MAXX(SKUs, CALCULATE([Promo Lift %]))
			VAR FreqRange = MaxFreq - MinFreq
			VAR LiftRange = MaxLift - MinLift
			VAR ZeroY = OriginY + PlotH - DIVIDE(0 - MinLift, LiftRange) * PlotH
			VAR Points =
			    CONCATENATEX(
			        SKUs,
			        VAR Freq = CALCULATE([Promo Frequency %])
			        VAR Lift = CALCULATE([Promo Lift %])
			        VAR CX = OriginX + DIVIDE(Freq - MinFreq, FreqRange) * PlotW
			        VAR CY = OriginY + PlotH - DIVIDE(Lift - MinLift, LiftRange) * PlotH
			        VAR Color =
			            SWITCH(
			                TRUE(),
			                Freq >= FreqThreshold && Lift >= LiftThreshold, "#1f6b45",
			                Freq >= FreqThreshold && Lift < LiftThreshold, "#c0392b",
			                "#c9932e"
			            )
			        RETURN
			        "<circle cx='" & FORMAT(CX, "0.0") & "' cy='" & FORMAT(CY, "0.0") & "' r='4.5' fill='" & Color & "'/>",
			        ""
			    )
			VAR RiskCount =
			    COUNTX(
			        FILTER(SKUs, CALCULATE([Promo Frequency %]) >= FreqThreshold && CALCULATE([Promo Lift %]) < LiftThreshold),
			        Dim_Product[sku]
			    )
			VAR RiskSpend =
			    SUMX(
			        FILTER(SKUs, CALCULATE([Promo Frequency %]) >= FreqThreshold && CALCULATE([Promo Lift %]) < LiftThreshold),
			        CALCULATE(SUMX('Fact', Fact[units_sold] * Fact[price_unit]), Fact[promotion_flag] = 1)
			    )
			VAR InsightText =
			    RiskCount & " SKUs sit high-frequency, low-lift — repeated discounting with no incremental gain, ~AED " &
			    FORMAT(RiskSpend / 1000000, "0.0") & "M trade spend at risk."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:14px;font-family:sans-serif'>" &
			"<div style='font-size:12px;font-weight:600;color:#1a1a1a;margin-bottom:2px'>Promo frequency vs promo lift &middot; by SKU</div>" &
			"<div style='font-size:10px;color:#9a9a92;margin-bottom:10px'>Bottom right = discount dependency</div>" &
			"<svg viewBox='0 0 300 100' xmlns='http://www.w3.org/2000/svg'>" &
			"<line x1='" & OriginX & "' y1='" & OriginY & "' x2='" & OriginX & "' y2='90' stroke='#e2e0d8' stroke-width='1'/>" &
			"<line x1='" & OriginX & "' y1='" & FORMAT(ZeroY, "0.0") & "' x2='290' y2='" & FORMAT(ZeroY, "0.0") & "' stroke='#e2e0d8' stroke-width='1'/>" &
			"<text x='288' y='" & FORMAT(ZeroY - 6, "0.0") & "' text-anchor='end' font-size='7.5' fill='#1f6b45'>good investment</text>" &
			"<text x='288' y='" & FORMAT(ZeroY + 12, "0.0") & "' text-anchor='end' font-size='7.5' fill='#b23b3b'>discount dependency</text>" &
			Points &
			"</svg>" &
			"<div style='background:#fbe4e4;border-radius:4px;padding:8px 10px;margin-top:8px;font-size:10.5px;color:#8a2f2f;line-height:1.5'>&#10022; " &
			InsightText &
			"</div>" &
			"</div>"
		lineageTag: ad17ef96-5b26-4e63-bb8f-ddd60171de62

	measure 'Stock Risk Scatter Card' =
			
			VAR PlotW = 260
			VAR PlotH = 82
			VAR OriginX = 30
			VAR OriginY = 8
			VAR SKUs = VALUES(Dim_Product[sku])
			VAR MinStock = MINX(SKUs, CALCULATE(AVERAGE(Fact[stock_available])))
			VAR MaxStock = MAXX(SKUs, CALCULATE(AVERAGE(Fact[stock_available])))
			VAR MinDemand = MINX(SKUs, CALCULATE([Avg Units Sold]))
			VAR MaxDemand = MAXX(SKUs, CALCULATE([Avg Units Sold]))
			VAR StockRange = MaxStock - MinStock
			VAR DemandRange = MaxDemand - MinDemand
			VAR StockThreshold = PERCENTILEX.INC(SKUs, CALCULATE(AVERAGE(Fact[stock_available])), 0.25)
			VAR DemandThreshold = PERCENTILEX.INC(SKUs, CALCULATE([Avg Units Sold]), 0.60)
			VAR Points =
			    CONCATENATEX(
			        SKUs,
			        VAR Stock = CALCULATE(AVERAGE(Fact[stock_available]))
			        VAR Demand = CALCULATE([Avg Units Sold])
			        VAR CX = OriginX + DIVIDE(Stock - MinStock, StockRange) * PlotW
			        VAR CY = OriginY + PlotH - DIVIDE(Demand - MinDemand, DemandRange) * PlotH
			        VAR IsRisk = Stock <= StockThreshold && Demand >= DemandThreshold
			        RETURN
			        "<circle cx='" & FORMAT(CX, "0.0") & "' cy='" & FORMAT(CY, "0.0") & "' r='" & IF(IsRisk, 5.5, 4.5) & "' fill='" & IF(IsRisk, "#c0392b", "#cfe4d6") & "'/>",
			        ""
			    )
			VAR RiskCount =
			    COUNTX(
			        FILTER(SKUs, CALCULATE(AVERAGE(Fact[stock_available])) <= StockThreshold && CALCULATE([Avg Units Sold]) >= DemandThreshold),
			        Dim_Product[sku]
			    )
			VAR InsightText =
			    RiskCount & " SKUs sit in the stockout alert zone — high rolling demand against thin available stock."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:14px;font-family:sans-serif'>" &
			"<div style='font-size:12px;font-weight:600;color:#1a1a1a;margin-bottom:2px'>Stock risk matrix</div>" &
			"<div style='font-size:10px;color:#9a9a92;margin-bottom:10px'>Demand vs stock available</div>" &
			"<svg viewBox='0 0 300 100' xmlns='http://www.w3.org/2000/svg'>" &
			"<line x1='" & OriginX & "' y1='" & OriginY & "' x2='" & OriginX & "' y2='90' stroke='#e2e0d8' stroke-width='1'/>" &
			"<line x1='" & OriginX & "' y1='90' x2='290' y2='90' stroke='#e2e0d8' stroke-width='1'/>" &
			Points &
			"</svg>" &
			"<div style='background:#fbe4e4;border-radius:4px;padding:8px 10px;margin-top:8px;font-size:10.5px;color:#8a2f2f;line-height:1.5'>&#10022; " &
			InsightText &
			"</div>" &
			"</div>"
		lineageTag: 9e0f9f5c-54e8-4a7d-8a50-7197027d25dd

	measure 'PostPromoDip %' =
			
			VAR LastPromoDate = CALCULATE(MAX(Fact[date]), Fact[promotion_flag] = 1)
			VAR PostAvg =
			    CALCULATE([Avg Units Sold], Fact[date] > LastPromoDate && Fact[date] <= LastPromoDate + 28)
			RETURN DIVIDE(PostAvg - [Baseline Sales], [Baseline Sales])
		lineageTag: 0ef6da53-2348-454f-8501-1af18de42c1d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Stock Risk Callout Card' =
			
			VAR Combos = SUMMARIZE('Fact', Fact[region], Fact[channel])
			VAR RankedCombos =
			    ADDCOLUMNS(
			        Combos,
			        "@Rate", CALCULATE(DIVIDE(CALCULATE(COUNTROWS(Fact), Fact[stock_available] <= 5), COUNTROWS(Fact)))
			    )
			VAR TopCombo = TOPN(1, RankedCombos, [@Rate], DESC)
			VAR TopRegion = MAXX(TopCombo, Fact[region])
			VAR TopChannel = MAXX(TopCombo, Fact[channel])
			VAR TopRate = MAXX(TopCombo, [@Rate])
			VAR InsightText =
			    TopRegion & " region " & TopChannel & " channel shows a " & FORMAT(TopRate, "0%") &
			    " stockout rate. Raise safety stock for the top 5 SKUs before the next peak period."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;border-left:3px solid #c0392b;font-family:sans-serif'>" &
			"<div style='font-size:11px;font-weight:600;color:#8a2f2f;margin-bottom:4px'>Stock risk</div>" &
			"<div style='font-size:10.5px;color:#4a4a44;line-height:1.55'>" & InsightText & "</div></div>"
		lineageTag: 80dd9fe3-c0ac-4874-b6ca-83cc17b5b5d4

	measure 'Budget Shift Callout Card' =
			
			VAR ChannelROI = ADDCOLUMNS(VALUES(Fact[channel]), "@ROI", CALCULATE([Overall Promo ROI]))
			VAR BestChannel = TOPN(1, ChannelROI, [@ROI], DESC)
			VAR WorstChannel = TOPN(1, ChannelROI, [@ROI], ASC)
			VAR BestName = MAXX(BestChannel, Fact[channel])
			VAR BestROI = MAXX(BestChannel, [@ROI])
			VAR WorstName = MAXX(WorstChannel, Fact[channel])
			VAR WorstROI = MAXX(WorstChannel, [@ROI])
			VAR Multiple = DIVIDE(BestROI, WorstROI)
			VAR InsightText =
			    "Promo ROI in " & BestName & " is " & FORMAT(Multiple, "0.0") & "x higher than " & WorstName &
			    " channel. Shift 20% of trade budget from " & WorstName & " to " & BestName & " in H1."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;border-left:3px solid #1f6b45;font-family:sans-serif'>" &
			"<div style='font-size:11px;font-weight:600;color:#1f6b45;margin-bottom:4px'>Budget shift</div>" &
			"<div style='font-size:10.5px;color:#4a4a44;line-height:1.55'>" & InsightText & "</div></div>"
		lineageTag: a5dfcbb1-8686-45ce-84f2-6b97ed034719

	measure 'Seasonality Callout Card' =
			
			VAR TopSKU = MAXX(TOPN(1, VALUES(Dim_Product[sku]), CALCULATE([Avg Units Sold]), DESC), Dim_Product[sku])
			VAR MonthlyAvg =
			    ADDCOLUMNS(
			        VALUES(Dim_Date[month_name]),
			        "@U", CALCULATE([Avg Units Sold], Dim_Product[sku] = TopSKU)
			    )
			VAR PeakMonth = MAXX(TOPN(1, MonthlyAvg, [@U], DESC), Dim_Date[month_name])
			VAR PeakVal = MAXX(TOPN(1, MonthlyAvg, [@U], DESC), [@U])
			VAR TroughMonth = MAXX(TOPN(1, MonthlyAvg, [@U], ASC), Dim_Date[month_name])
			VAR TroughVal = MAXX(TOPN(1, MonthlyAvg, [@U], ASC), [@U])
			VAR DropPct = DIVIDE(PeakVal - TroughVal, PeakVal)
			VAR InsightText =
			    TopSKU & " demand peaks in " & PeakMonth & " and drops " & FORMAT(DropPct, "0%") &
			    " by " & TroughMonth & ". Align production and distribution to this seasonal pattern."
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;border-left:3px solid #c9932e;font-family:sans-serif'>" &
			"<div style='font-size:11px;font-weight:600;color:#a3641f;margin-bottom:4px'>Seasonality</div>" &
			"<div style='font-size:10.5px;color:#4a4a44;line-height:1.55'>" & InsightText & "</div></div>"
		lineageTag: d0a9b41b-b1e8-4743-9908-129897bb1a77

	measure 'Units This Month' = SUM(Fact[units_sold])
		formatString: 0
		lineageTag: bd0ed9e1-0d7e-4130-9439-0120b97f482b

	measure 'Units Prior Month' = ```
			
			CALCULATE(
			    [Units This Month],
			    DATEADD(Dim_Date[date], -1, MONTH)
			)
			
			```
		formatString: 0
		lineageTag: 1c9144e2-4845-47e4-8ea7-c2c8b74a247e

	measure 'Momentum %' =
			
			DIVIDE(
			    [Units This Month] - [Units Prior Month],
			    [Units Prior Month]
			)
		lineageTag: 5e001419-c5fe-478b-bf31-f3be1bfef93d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Momentum Table Card' =
			
			VAR MomentumBySKU = ADDCOLUMNS(VALUES(Dim_Product[sku]), "@M", CALCULATE([Momentum %]))
			VAR TopAccel = TOPN(2, MomentumBySKU, [@M], DESC)
			VAR TopDecel = TOPN(2, MomentumBySKU, [@M], ASC)
			VAR TopAccelBest = MAXX(TopAccel, [@M])
			VAR TopDecelWorst = MINX(TopDecel, [@M])
			VAR AccelRows =
			    CONCATENATEX(
			        TopAccel,
			        VAR SKUName = [sku]
			        VAR MVal = [@M]
			        VAR ActionText = IF(MVal = TopAccelBest, "expand distro", "increase stock")
			        RETURN
			        "<tr><td style='padding:5px 0;color:#1f6b45'>&#9650; " & SKUName & "</td><td style='text-align:right;color:#1a1a1a'>" & FORMAT(MVal, "+0.0%;-0.0%") & "</td><td style='text-align:right;color:#6b6b63'>" & ActionText & "</td></tr>",
			        "", [@M], DESC
			    )
			VAR DecelRows =
			    CONCATENATEX(
			        TopDecel,
			        VAR SKUName = [sku]
			        VAR MVal = [@M]
			        VAR ActionText = IF(MVal = TopDecelWorst, "review promo", "reduce SKU count")
			        RETURN
			        "<tr><td style='padding:5px 0;color:#b23b3b'>&#9660; " & SKUName & "</td><td style='text-align:right;color:#1a1a1a'>" & FORMAT(MVal, "+0.0%;-0.0%") & "</td><td style='text-align:right;color:#6b6b63'>" & ActionText & "</td></tr>",
			        "", [@M], ASC
			    )
			VAR TopAccelSKU = MAXX(TOPN(1, TopAccel, [@M], DESC), [sku])
			VAR TopAccelPromoLift = CALCULATE([Promo Lift %], Dim_Product[sku] = TopAccelSKU)
			VAR TopAccelDip = CALCULATE([PostPromoDip %], Dim_Product[sku] = TopAccelSKU)
			VAR InsightText =
			    TopAccelSKU & " spiked " & FORMAT(TopAccelPromoLift, "0%") &
			    " during promo but ran " & FORMAT(ABS(TopAccelDip), "0%") &
			    IF(TopAccelDip < 0, " below", " above") & " baseline for the 4 weeks after — " &
			    IF(TopAccelDip < 0, "classic pantry loading, volume borrowed not incremental.", "sustained lift, incremental volume likely.")
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:14px;font-family:sans-serif'>" &
			"<div style='font-size:12px;font-weight:600;color:#1a1a1a;margin-bottom:10px'>Momentum leaders &amp; laggards</div>" &
			"<table style='width:100%;font-size:10.5px;border-collapse:collapse'>" &
			"<tr style='color:#9a9a92'><td style='padding:4px 0'>SKU</td><td style='text-align:right'>momentum</td><td style='text-align:right'>action</td></tr>" &
			AccelRows & DecelRows &
			"</table>" &
			"<div style='background:#fbe4e4;border-radius:4px;padding:8px 10px;margin-top:10px;font-size:10.5px;color:#8a2f2f;line-height:1.5'>&#10022; " &
			InsightText & "</div></div>"
		lineageTag: e5310e9c-3341-4eb1-8c58-e4429f0aa08b

	measure 'Stockout Risk SKU Count' = ```
			
			VAR SKUs = VALUES(Dim_Product[sku])
			VAR StockThreshold = PERCENTILEX.INC(SKUs, CALCULATE(AVERAGE(Fact[stock_available])), 0.25)
			VAR DemandThreshold = PERCENTILEX.INC(SKUs, CALCULATE([Avg Units Sold]), 0.60)
			RETURN
			COUNTX(
			    FILTER(SKUs, CALCULATE(AVERAGE(Fact[stock_available])) <= StockThreshold && CALCULATE([Avg Units Sold]) >= DemandThreshold),
			    Dim_Product[sku]
			)
			
			```
		formatString: 0
		lineageTag: 1e81ee3e-8758-4e4b-a927-c7e98303b565

	measure 'Forecast Trend %' =
			
			VAR LastFactDate = MAX(Fact[date])
			VAR Last4Wk =
			    CALCULATE(
			        [Units This Month],
			        Fact[date] > LastFactDate - 28 && Fact[date] <= LastFactDate
			    )
			VAR Prior4Wk =
			    CALCULATE(
			        [Units This Month],
			        Fact[date] > LastFactDate - 56 && Fact[date] <= LastFactDate - 28
			    )
			RETURN
			DIVIDE(Last4Wk - Prior4Wk, Prior4Wk)
		lineageTag: a0d5bcb5-9790-4cfc-9ce3-fc4cee90afcc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Card Promo ROI' =
			
			VAR ROI = [Overall Promo ROI]
			VAR IsGood = ROI >= 1
			VAR BadgeColor = IF(IsGood, "#1f6b45", "#b23b3b")
			VAR BadgeBg = IF(IsGood, "#e2f0e5", "#fbe4e4")
			VAR BadgeText = IF(IsGood, "&#9650; vs baseline", "&#9660; below baseline")
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;font-family:sans-serif'>" &
			"<div style='font-size:10px;letter-spacing:0.05em;color:#8a8a82;text-transform:uppercase'>Overall promo ROI</div>" &
			"<div style='font-size:22px;font-weight:600;color:#1a1a1a;margin-top:4px'>" & FORMAT(ROI, "0.0") & "x</div>" &
			"<div style='display:inline-block;margin-top:6px;font-size:10px;color:" & BadgeColor & ";background:" & BadgeBg & ";padding:2px 7px;border-radius:4px'>" & BadgeText & "</div>" &
			"</div>"
		lineageTag: b63a114d-a0f4-4421-8910-ff36aa5f6219

	measure 'KPI Card Promo Frequency' =
			
			VAR Freq = [Promo Frequency %]
			VAR IsOverPromoted = Freq > 0.30
			VAR BadgeColor = IF(IsOverPromoted, "#a3641f", "#1f6b45")
			VAR BadgeBg = IF(IsOverPromoted, "#faf1e0", "#e2f0e5")
			VAR BadgeText = IF(IsOverPromoted, "over-promoted", "healthy mix")
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;font-family:sans-serif'>" &
			"<div style='font-size:10px;letter-spacing:0.05em;color:#8a8a82;text-transform:uppercase'>Promo frequency</div>" &
			"<div style='font-size:22px;font-weight:600;color:#1a1a1a;margin-top:4px'>" & FORMAT(Freq, "0%") & "</div>" &
			"<div style='display:inline-block;margin-top:6px;font-size:10px;color:" & BadgeColor & ";background:" & BadgeBg & ";padding:2px 7px;border-radius:4px'>" & BadgeText & "</div>" &
			"</div>"
		lineageTag: 13ed4edc-6dcf-4bae-84e4-76f4d5511265

	measure 'KPI Card Stockout Risk' =
			
			VAR RiskCount = [Stockout Risk SKU Count]
			VAR HasRisk = RiskCount > 0
			VAR BadgeColor = IF(HasRisk, "#b23b3b", "#1f6b45")
			VAR BadgeBg = IF(HasRisk, "#fbe4e4", "#e2f0e5")
			VAR BadgeText = IF(HasRisk, "action required", "no risk")
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;font-family:sans-serif'>" &
			"<div style='font-size:10px;letter-spacing:0.05em;color:#8a8a82;text-transform:uppercase'>SKUs at stockout risk</div>" &
			"<div style='font-size:22px;font-weight:600;color:#1a1a1a;margin-top:4px'>" & RiskCount & "</div>" &
			"<div style='display:inline-block;margin-top:6px;font-size:10px;color:" & BadgeColor & ";background:" & BadgeBg & ";padding:2px 7px;border-radius:4px'>" & BadgeText & "</div>" &
			"</div>"
		lineageTag: 3525fb8f-3862-4d5e-a999-6aaa3f935cd9

	measure 'KPI Card Forecast Trend' =
			
			VAR Trends = [Forecast Trend %]
			VAR IsUp = Trends >= 0
			VAR BadgeColor = IF(IsUp, "#1f6b45", "#b23b3b")
			VAR BadgeBg = IF(IsUp, "#e2f0e5", "#fbe4e4")
			VAR BadgeText = IF(IsUp, "&#9650; vs current run rate", "&#9660; vs current run rate")
			RETURN
			"<div style='background:#ffffff;border-radius:6px;padding:12px 14px;font-family:sans-serif'>" &
			"<div style='font-size:10px;letter-spacing:0.05em;color:#8a8a82;text-transform:uppercase'>4-week forecast</div>" &
			"<div style='font-size:22px;font-weight:600;color:#1a1a1a;margin-top:4px'>" & FORMAT(Trends, "+0.0%;-0.0%") & "</div>" &
			"<div style='display:inline-block;margin-top:6px;font-size:10px;color:" & BadgeColor & ";background:" & BadgeBg & ";padding:2px 7px;border-radius:4px'>" & BadgeText & "</div>" &
			"</div>"
		lineageTag: 5c09ad78-785b-4793-b359-461409d57abf

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

