table _Measures
	lineageTag: ab04c4a4-5f0c-4a86-a69c-14d142e6eb1e

	measure 'Total Revenue' =
			
			SUM ( Fact[Sales Amount] )
		lineageTag: e81d7dbf-c154-44b5-8bf0-d0e930a86253

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2024' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2024 )
			
			```
		lineageTag: 29172e91-ab0f-41ab-8a72-23f61df6203c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2023' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2023 )
			
			```
		lineageTag: d0e3180e-8c4c-4661-b85e-9a26ef1b7c03

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Revenue 2022' = ```
			
			CALCULATE ( [Total Revenue], Dim_Date[year] = 2022 )
			
			```
		lineageTag: 037b69ab-9510-483a-96d8-1fff85ccabe3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue YoY %' =
			
			DIVIDE ( [Total Revenue 2024] - [Total Revenue 2023], [Total Revenue 2023], 0 )
		lineageTag: 1c98e2df-69b8-48f9-be5a-134f4679bce0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Target' =
			
			SUMX ( Dim_Target, VALUE ( Dim_Target[Sales_Target] ) )
		lineageTag: 7bf1e802-6ab8-4359-8bdb-290fddc89c69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achievement %' =
			
			VAR TargetYear = VALUE ( SELECTEDVALUE ( Dim_Target[Year], "2024" ) )
			VAR RevenueSamePeriod =
			    CALCULATE ( [Total Revenue], Dim_Date[year] = TargetYear )
			RETURN
			    DIVIDE ( RevenueSamePeriod, [Total Target], 0 )
		lineageTag: 1bb2c99b-89f1-46c8-aa2d-c259b70765fc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Variance (AED)' =
			
			VAR TargetYear = VALUE ( SELECTEDVALUE ( Dim_Target[Year], "2024" ) )
			VAR RevenueSamePeriod =
			    CALCULATE ( [Total Revenue], Dim_Date[year] = TargetYear )
			RETURN
			    RevenueSamePeriod - [Total Target]
		lineageTag: ca93b706-5534-44d3-95fb-08ddb62f476b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Achievement Status' = ```
			
			SWITCH (
			    TRUE (),
			    [Achievement %] >= 1,    "On Target",
			    [Achievement %] >= 0.9,  "Near Target",
			    "Below Target"
			)
			
			```
		lineageTag: 517db952-1946-49f7-a4af-3e0dd0fd72c2

	measure 'Active Outlets' =
			
			DISTINCTCOUNT ( Fact[outlet_id] )
		formatString: 0
		lineageTag: d90bd69a-d483-41e7-a6d4-5cab463bbfbb

	measure 'Outlet Universe' = ```
			
			COUNTROWS ( Dim_outlet )
			
			```
		formatString: 0
		lineageTag: ec828cb2-df37-445b-bab2-3603c478a8d4

	measure 'Outlet Coverage %' = ```
			
			DIVIDE ( [Active Outlets], [Outlet Universe], 0 )
			
			```
		lineageTag: 1d03f3c1-6ad3-4a8c-a603-c42513f4ea4e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Revenue per Outlet' = ```
			
			DIVIDE ( [Total Revenue], [Active Outlets], 0 )
			
			```
		lineageTag: 82d2dc7c-157d-46c8-9cc9-c1ed27946ffb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Revenue per Outlet 2024' =
			
			DIVIDE ( [Total Revenue 2024], [Active Outlets], 0 )
		lineageTag: 3d1dcdfd-f67f-40d5-9f66-5b6196d29a53

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distributor Rank' =
			
			RANKX ( ALLSELECTED ( Fact[distributor_name] ), [Total Revenue], , DESC, Dense )
		formatString: 0
		lineageTag: 06d753d7-1d88-4068-bc69-0dd58552279b

	measure 'Top Distributor' =
			
			VAR T = TOPN ( 1, ALLSELECTED ( Fact[distributor_name] ), [Total Revenue], DESC )
			RETURN
			    MAXX ( T, Fact[distributor_name] )
		lineageTag: 7ceec4d3-e3e2-4db6-8346-699df4b2060f

	measure 'Distribution Index' = ```
			
			[Outlet Coverage %] * 100
			
			```
		lineageTag: 36045b38-37fd-4e15-99ea-5ea10d49c024

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Promo Compliance Index' = ```
			
			AVERAGE ( Fact[promotion_flag] ) * 100
			
			```
		lineageTag: d7753f76-26ae-474b-8d05-1f28a38b18b4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sales Achievement Index' = ```
			
			MIN ( [Achievement %] * 100, 100 )
			
			```
		lineageTag: 3fe6a955-d4a2-4347-ba90-838d085f3e69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CD Health Score' = ```
			
			( [Distribution Index] + [Promo Compliance Index] + [Sales Achievement Index] ) / 3
			
			```
		lineageTag: 780a9b04-21e2-4960-87b6-d6db358034ae

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Health Score Status' =
			
			SWITCH (
			    TRUE (),
			    [CD Health Score] >= 80, "Strong",
			    [CD Health Score] >= 60, "Moderate",
			    "Needs Attention"
			)
		lineageTag: 24c551e7-a342-4a1b-a44a-757083687515

	measure 'Revenue (Current Year)' = [Total Revenue 2024]
		lineageTag: 9df5c348-9a42-46bf-83e0-f25cef8b0d42

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue (Prior Year)' = [Total Revenue 2023]
		lineageTag: 65e91817-7d4d-41b5-aad0-3df4d0573296

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI HTML - Achievement' =
			
			VAR _Status   = [Achievement Status]
			VAR _AchPct   = [Achievement %]
			VAR _Color    = SWITCH ( TRUE (), _AchPct >= 1, "#2C5C3C", _AchPct >= 0.9, "#8C5C0D", "#8C2E20" )
			VAR _Bg       = SWITCH ( TRUE (), _AchPct >= 1, "#E7F2EB", _AchPct >= 0.9, "#FAF1DF", "#F8E8E4" )
			VAR _Accent   = SWITCH ( TRUE (), _AchPct >= 1, "#3F7D52", _AchPct >= 0.9, "#BE7A12", "#B23E2B" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid " & _Accent & ";
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>ACHIEVEMENT</div>" &
			"<div style='font-size:28px;font-weight:700;color:" & _Color & ";line-height:1;'>" & FORMAT ( _AchPct, "0.0%" ) & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>vs 100% target</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Status & "</div>" &
			"</div>"
		lineageTag: 9f26d9ea-f3c6-47ff-a38e-bcd1d759acbe

	measure 'KPI HTML - Avg Per Outlet' =
			
			VAR _Avg      = [Avg Revenue per Outlet 2024]
			VAR _PriorAvg = DIVIDE ( [Total Revenue 2023], CALCULATE ( DISTINCTCOUNT ( Fact[outlet_id] ), Dim_Date[year] = 2023 ), 0 )
			VAR _Delta    = DIVIDE ( _Avg - _PriorAvg, _PriorAvg, 0 )
			VAR _Color    = IF ( _Delta >= 0, "#2C5C3C", "#8C2E20" )
			VAR _Bg       = IF ( _Delta >= 0, "#E7F2EB", "#F8E8E4" )
			VAR _Sign     = IF ( _Delta >= 0, "+", "-" )
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #9B870C;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>AVG REVENUE / OUTLET</div>" &
			"<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>AED " & FORMAT ( _Avg, "#,##0," ) & "K</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>annualised, 2024</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _Sign & FORMAT ( ABS ( _Delta ), "0.0%" ) & " vs 2023</div>" &
			"</div>"
		lineageTag: 4e19ff48-ebf5-423a-82e5-79a131780c62

	measure 'KPI HTML - Outlet Coverage' =
			
			VAR _Coverage = [Outlet Coverage %]
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #0D5C56;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>OUTLET COVERAGE</div>" &
			"<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>" &
			[Active Outlets] & "<span style='font-size:14px;font-weight:500;color:#67726C;'> / " & [Outlet Universe] & "</span></div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>active outlets of universe</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:#E2EFEE;color:#0D5C56;'>" & FORMAT ( _Coverage, "0.0%" ) & " covered</div>" &
			"</div>"
		lineageTag: fae89983-1af8-4e90-8d2f-100eb2554b99

	measure 'KPI HTML - Revenue' = ```
			
			VAR _Status      = [Achievement Status]
			VAR _AchPct      = [Achievement %]
			VAR _Color       = SWITCH ( TRUE (), _AchPct >= 1, "#2C5C3C", _AchPct >= 0.9, "#8C5C0D", "#8C2E20" )
			VAR _Bg          = SWITCH ( TRUE (), _AchPct >= 1, "#E7F2EB", _AchPct >= 0.9, "#FAF1DF", "#F8E8E4" )
			VAR _ValueText   = "AED " & FORMAT ( [Total Revenue 2024], "#,##0,,.0" ) & "M"
			VAR _TargetText  = "Target AED " & FORMAT ( [Total Target], "#,##0,,.0" ) & "M"
			VAR _VarSign     = IF ( [Revenue Variance (AED)] >= 0, "+", "-" )
			VAR _VarText     = _VarSign & "AED " & FORMAT ( ABS ( [Revenue Variance (AED)] ), "#,##0,,.0" ) & "M"
			RETURN
			"<div style='font-family:Segoe UI,Arial,sans-serif;background:#FFFFFF;border-top:3px solid #0D5C56;
			border-radius:10px;padding:16px 18px;height:90%;box-sizing:border-box;'>" &
			"<div style='font-size:10px;font-weight:700;letter-spacing:1px;color:#67726C;text-transform:uppercase;
			margin-bottom:8px;'>TOTAL REVENUE 2024</div>" &
			"<div style='font-size:28px;font-weight:700;color:#1C2624;line-height:1;'>" & _ValueText & "</div>" &
			"<div style='font-size:11px;color:#67726C;margin:8px 0 10px;'>" & _TargetText & "</div>" &
			"<div style='display:inline-block;font-size:11px;font-weight:600;padding:3px 9px;border-radius:6px;
			background:" & _Bg & ";color:" & _Color & ";'>" & _VarText & "</div>" &
			"</div>"
			
			```
		lineageTag: 2d50162a-e20c-4658-ae0d-edf6530703c7

	measure 'KPI HTML - CD Health Score' = ```
			
			VAR Score    = ROUND([CD Health Score], 0)
			VAR DistVal  = ROUND([Distribution Index], 0)
			VAR PromoVal = ROUND([Promo Compliance Index], 0)
			VAR SalesVal = ROUND([Sales Achievement Index], 0)
			
			-- Donut math (radius = 40, circumference = 2π×40 ≈ 251.2)
			VAR Circ    = 251.2
			VAR Filled  = DIVIDE(Score, 100) * Circ
			VAR Gap     = Circ - Filled
			
			-- Bar widths (max bar = 180px)
			VAR DistW   = DIVIDE(DistVal,  100) * 180
			VAR PromoW  = DIVIDE(PromoVal, 100) * 180
			VAR SalesW  = DIVIDE(SalesVal, 100) * 180
			
			RETURN
			
			"<div style='display:flex;align-items:center;gap:20px;padding:20px;box-sizing:border-box;background:#FFFFFF;
			             font-family:""Segoe UI"",sans-serif'>" 
			&
			
			  -- DONUT SVG
			  "<svg width='110' height='110' viewBox='0 0 110 110'>" &
			    "<circle cx='55' cy='55' r='40' fill='none'
			             stroke='#E8E4DC' stroke-width='10'/>" &
			    "<circle cx='55' cy='55' r='40' fill='none'
			             stroke='#C8972B' stroke-width='10'
			             stroke-dasharray='" & Filled & " " & Gap & "'
			             stroke-linecap='round'
			             transform='rotate(-90 55 55)'/>" &
			    "<text x='55' y='50' text-anchor='middle'
			           font-size='17' font-weight='700' fill='#C8972B'>" & Score & "</text>" &
			    "<text x='55' y='65' text-anchor='middle'
			           font-size='10' fill='#999'>/ 100</text>" &
			  "</svg>" &
			
			  -- BARS
			  "<div style='flex:1'>" &
			
			    -- Distribution
			    "<div style='margin-bottom:10px'>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size='12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Distribution</span>" &
			        "<span style='font-weight:600;color:#222'>" & DistVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#1A5C5A;width:" & DistW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			    -- Promo Compliance
			    "<div style='margin-bottom:10px'>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size:12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Promo Compliance</span>" &
			        "<span style='font-weight:600;color:#222'>" & PromoVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#C8972B;width:" & PromoW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			    -- Sales Achievement
			    "<div>" &
			      "<div style='display:flex;justify-content:space-between;
			                   font-size:12px;margin-bottom:4px'>" &
			        "<span style='color:#555'>Sales Achievement</span>" &
			        "<span style='font-weight:600;color:#222'>" & SalesVal & "</span>" &
			      "</div>" &
			      "<div style='background:#E8E4DC;border-radius:4px;height:7px'>" &
			        "<div style='background:#8B1A1A;width:" & SalesW & "px;
			                     height:7px;border-radius:4px'></div>" &
			      "</div>" &
			    "</div>" &
			
			  "</div>" &
			"</div>"
			```
		lineageTag: d08f19cf-19cb-4c67-b168-d986f0403b71

	measure 'KPI HTML - Territory Achievement' = ```
			
			VAR _Pct    = [Achievement %]   
			VAR _Txt    = FORMAT(_Pct * 100, "0.0") & "%"
			VAR _Arc    = IF(_Pct >= 1, "#1A5C5A", "#C0392B")
			VAR _Status = IF(_Pct >= 1, "On Target", "Below Target")
			VAR _PillBg = IF(_Pct >= 1, "#E3EEE0", "#FCEAEA")
			VAR _PillFg = IF(_Pct >= 1, "#1A5C5A", "#8B1A1A")
			
			-- 180° gauge  |  r=75  |  half-circumference = 235.6
			-- 0% = left (9 o'clock)   120% = right (3 o'clock)
			VAR _H    = 240
			VAR _Fill = DIVIDE(MIN(_Pct, 1.2), 1.2) * _H
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>"
			 &
			"<p style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222;margin:0 0 2px'>TERRITORY ACHIEVEMENT</p>" &
			"<div style='text-align:center'>" &
			"<svg width='220' height='132' viewBox='0 0 220 132'>" &
			
			  -- Gray background track (full 180°)
			  "<circle cx='110' cy='115' r='75' fill='none' stroke='#E8E4DC' stroke-width='14'" &
			  " stroke-dasharray='" & _H & " " & _H & "' transform='rotate(180 110 115)'/>" &
			
			  -- Colored fill arc
			  "<circle cx='110' cy='115' r='75' fill='none' stroke='" & _Arc & "' stroke-width='14'" &
			  " stroke-dasharray='" & _Fill & " 999' stroke-linecap='round'" &
			  " transform='rotate(180 110 115)'/>" &
			
			  -- White tick at 100% position (30° from right = upper-right of arc)
			  "<line x1='169' y1='81' x2='181' y2='74' stroke='white' stroke-width='2.5'/>" &
			
			  -- Percentage value
			  "<text x='110' y='92' text-anchor='middle' font-size='26' font-weight='700'" &
			  " fill='" & _Arc & "'>" & _Txt & "</text>" &
			
			  -- Status pill
			  "<rect x='57' y='97' width='106' height='18' rx='9' fill='" & _PillBg & "'/>" &
			  "<text x='110' y='110' text-anchor='middle' font-size='9'" &
			  " fill='" & _PillFg & "' font-weight='600'>● " & _Status & "</text>" &
			
			  -- Axis labels: 0% left · 100% upper-right · 120% right
			  "<text x='18'  y='124' text-anchor='middle' font-size='8.5' fill='#bbb'>0%</text>"  &
			  "<text x='183' y='62'  text-anchor='middle' font-size='8.5' fill='#bbb'>100%</text>" &
			  "<text x='202' y='124' text-anchor='middle' font-size='8.5' fill='#bbb'>120%</text>" &
			
			"</svg></div>" &
			"<p style='font-size:10px;color:#aaa;text-align:center;margin:0'>" &
			"of 2024 revenue target — AED 10.6M</p>" &
			"</div>"
			```
		lineageTag: 991594ac-5962-4007-8f0d-2f7ca049fed6

	measure 'KPI HTML - Distributor Performance' = ```
			
			
			-- ① Base data
			VAR _All =
			    ADDCOLUMNS(
			        VALUES('Fact'[distributor_name]),         
			        "@Rev", [Revenue (Current Year)]
			    )
			
			VAR _MaxRev   = MAXX(_All, [@Rev])
			VAR _MaxBarPx = 200
			
			-- ② Top 5
			VAR _Top5 = TOPN(5, _All, [@Rev], DESC)
			
			VAR _Top5HTML =
			    CONCATENATEX(
			        _Top5,
			        VAR _rank = RANKX(_Top5, [@Rev],, DESC, Dense)
			        VAR _barW = DIVIDE([@Rev], _MaxRev) * _MaxBarPx
			        VAR _fmt  = IF([@Rev] >= 1000000,
			                       FORMAT([@Rev] / 1000000, "0.00") & "M",
			                       FORMAT([@Rev] / 1000, "#,0") & "K")
			        RETURN
			        "<div style='display:flex;align-items:center;gap:6px;margin-bottom:7px'>" &
			          "<span style='color:#aaa;font-size:10px;min-width:10px;text-align:right'>" & _rank & "</span>" &
			          "<span style='flex:1;font-size:11px;color:#333;white-space:nowrap;overflow:hidden'>"
			              & 'Fact'[distributor_name] & "</span>" &          -- ← REPLACE column
			          "<div style='width:" & _MaxBarPx & "px;background:#EDEBE5;border-radius:3px;height:5px;flex-shrink:0'>" &
			            "<div style='background:#C4C0B8;width:" & _barW & "px;height:5px;border-radius:3px'></div>" &
			          "</div>" &
			          "<span style='font-size:10px;color:#333;min-width:50px;text-align:right'>" & _fmt & "</span>" &
			        "</div>",
			        "",
			        [@Rev], DESC
			    )
			
			-- ③ Bottom 4 (remaining, ranked worst first)
			VAR _Bottom4 = TOPN(4, _All, [@Rev], ASC)
			
			VAR _Bottom4HTML =
			    CONCATENATEX(
			        _Bottom4,
			        VAR _rank = RANKX(_Bottom4, [@Rev],, ASC, Dense)
			        VAR _barW = DIVIDE([@Rev], _MaxRev) * _MaxBarPx
			        VAR _fmt  = IF([@Rev] >= 1000000,
			                       FORMAT([@Rev] / 1000000, "0.00") & "M",
			                       FORMAT([@Rev] / 1000, "#,0") & "K")
			        RETURN
			        "<div style='display:flex;align-items:center;gap:6px;margin-bottom:7px'>" &
			          "<span style='color:#aaa;font-size:10px;min-width:10px;text-align:right'>" & _rank & "</span>" &
			          "<span style='flex:1;font-size:11px;color:#333;white-space:nowrap;overflow:hidden'>"
			              & 'Fact'[distributor_name] & "</span>" &          -- ← REPLACE column
			          "<div style='width:" & _MaxBarPx & "px;background:#EDEBE5;border-radius:3px;height:5px;flex-shrink:0'>" &
			            "<div style='background:#C4C0B8;width:" & _barW & "px;height:5px;border-radius:3px'></div>" &
			          "</div>" &
			          "<span style='font-size:10px;color:#333;min-width:50px;text-align:right'>" & _fmt & "</span>" &
			        "</div>",
			        "",
			        [@Rev], ASC
			    )
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>" &
			
			  "<div style='display:flex;justify-content:space-between;align-items:baseline;margin-bottom:12px'>" &
			    "<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222'>DISTRIBUTOR PERFORMANCE</span>" &
			    "<span style='font-size:10px;color:#aaa'>Sales value · AED</span>" &
			  "</div>" &
			
			  "<div style='font-size:9px;font-weight:700;letter-spacing:0.5px;color:#1A5C5A;margin-bottom:8px'>▲ TOP 5 PERFORMERS</div>" &
			  _Top5HTML &
			
			  "<div style='font-size:9px;font-weight:700;letter-spacing:0.5px;color:#8B1A1A;margin:12px 0 8px'>▼ BOTTOM 4 · ACTION REQUIRED</div>" &
			  _Bottom4HTML &
			
			"</div>"
			```
		lineageTag: 61425a98-68f4-4bd4-b58f-8cda8f9cf4a7

	measure 'KPI HTML - Revenue Trend' = ```
			
			
			VAR _YoY    = [Revenue YoY %]
			VAR _Sign   = IF(_YoY >= 0, "+", "")
			VAR _YoYTxt = _Sign & FORMAT(_YoY * 100, "0.0") & "% YoY"
			VAR _YoYBg  = IF(_YoY >= 0, "#E3EEE0", "#FCEAEA")
			VAR _YoYFg  = IF(_YoY >= 0, "#1A5C5A", "#8B1A1A")
			
			-- Chart canvas
			VAR _W     = 540   VAR _H     = 240
			VAR _PadL  = 38    VAR _PadR  = 8
			VAR _PadT  = 6     VAR _PadB  = 18
			VAR _PlotW = _W - _PadL - _PadR
			VAR _PlotH = _H - _PadT - _PadB
			VAR _XStep = DIVIDE(_PlotW, 11)
			
			-- Monthly revenue  ← REPLACE table/columns below
			
			VAR _Data =
			    ADDCOLUMNS(
			        GENERATESERIES(1,12,1),
			
			        "@R24",
			        VAR _Month = [Value]
			        RETURN
			        CALCULATE(
			            SUM('Fact'[Sales Amount]),
			            FILTER(
			                ALL('Dim_Date'),
			                'Dim_Date'[year] = 2024 &&
			                'Dim_Date'[month] = _Month
			            )
			        ),
			
			        "@R23",
			        VAR _Month2 = [Value]
			        RETURN
			        CALCULATE(
			            SUM('Fact'[Sales Amount]),
			            FILTER(
			                ALL('Dim_Date'),
			                'Dim_Date'[year] = 2023 &&
			                'Dim_Date'[month] = _Month2
			            )
			        )
			    )
			VAR _MaxRev = MAXX(_Data, MAX([@R24], [@R23]))
			VAR _MinRev = MINX(_Data, MIN([@R24], [@R23])) * 0.92   -- small padding below min
			
			-- SVG polyline point helpers
			VAR _Pts24 =
			    CONCATENATEX(
			        _Data,
			        VAR _x = _PadL + ([Value] - 1) * _XStep
			        VAR _y = _PadT + _PlotH
			              - DIVIDE(IF(ISBLANK([@R24]), _MinRev, [@R24]) - _MinRev, _MaxRev - _MinRev) * _PlotH
			        RETURN FORMAT(_x, "0.0") & "," & FORMAT(_y, "0.0"),
			        " ", [Value], ASC
			    )
			
			VAR _Pts23 =
			    CONCATENATEX(
			        _Data,
			        VAR _x = _PadL + ([Value] - 1) * _XStep
			        VAR _y = _PadT + _PlotH
			              - DIVIDE(IF(ISBLANK([@R23]), _MinRev, [@R23]) - _MinRev, _MaxRev - _MinRev) * _PlotH
			        RETURN FORMAT(_x, "0.0") & "," & FORMAT(_y, "0.0"),
			        " ", [Value], ASC
			    )
			
			-- Closed polygon for area fill
			VAR _BottomY = FORMAT(_PadT + _PlotH, "0")
			VAR _AreaPts = _Pts24
			    & " " & FORMAT(_PadL + 11 * _XStep, "0") & "," & _BottomY
			    & " " & FORMAT(_PadL, "0")                & "," & _BottomY
			
			-- December dot
			VAR _Dec24 = CALCULATE(SUM('Fact'[Sales Amount]), 'Dim_Date'[year]=2024, 'Dim_Date'[month]=12)  
			VAR _DotX  = _PadL + 11 * _XStep
			VAR _DotY  = _PadT + _PlotH
			           - DIVIDE(IF(ISBLANK(_Dec24), _MinRev, _Dec24) - _MinRev, _MaxRev - _MinRev) * _PlotH
			
			-- Y-axis labels
			VAR _MaxFmt = IF(_MaxRev>=1000000, FORMAT(_MaxRev/1000000,"0.#")&"M", FORMAT(_MaxRev/1000,"#,0")&"K")
			VAR _MinFmt = IF(_MinRev>=1000000, FORMAT(_MinRev/1000000,"0.#")&"M", FORMAT(_MinRev/1000,"#,0")&"K")
			
			-- Month labels
			VAR _MonthLbls =
			    CONCATENATEX(
			        GENERATESERIES(1, 12, 1),
			        VAR _x  = _PadL + ([Value] - 1) * _XStep
			        VAR _lbl = SWITCH([Value],1,"Jan",2,"Feb",3,"Mar",4,"Apr",5,"May",6,"Jun",
			                          7,"Jul",8,"Aug",9,"Sep",10,"Oct",11,"Nov",12,"Dec")
			        RETURN
			        "<text x='" & FORMAT(_x,"0") & "' y='" & FORMAT(_PadT + _PlotH + 12,"0") & "'" &
			        " text-anchor='middle' font-size='7.5' fill='#bbb'>" & _lbl & "</text>",
			        "", [Value], ASC
			    )
			
			RETURN
			"<div style='
			font-family:Segoe UI,sans-serif;
			padding:20px;
			background:#FFFFFF;
			border-radius:18px;
			height:100%;
			box-sizing:border-box;
			'>" &
			
			  "<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:10px'>" &
			    "<span style='font-size:10px;font-weight:700;letter-spacing:1px;color:#222'>REVENUE TREND · MONTH OVER MONTH</span>" &
			    "<span style='background:" & _YoYBg & ";color:" & _YoYFg & ";font-size:9px;font-weight:700;padding:3px 9px;border-radius:10px'>"
			        & _YoYTxt & "</span>" &
			  "</div>" &
			
			  "<svg width='" & _W & "' height='" & _H & "' viewBox='0 0 " & _W & " " & _H & "'>" &
			
			    -- Baseline + left axis
			    "<line x1='" & _PadL & "' y1='" & _PadT & "' x2='" & _PadL & "' y2='" & (_PadT+_PlotH) &
			    "' stroke='#E8E4DC' stroke-width='1'/>" &
			    "<line x1='" & _PadL & "' y1='" & (_PadT+_PlotH) & "' x2='" & (_W-_PadR) & "' y2='" & (_PadT+_PlotH) &
			    "' stroke='#E8E4DC' stroke-width='1'/>" &
			
			    -- Y labels
			    "<text x='" & (_PadL-4) & "' y='" & (_PadT+4) & "' text-anchor='end' font-size='8' fill='#bbb'>" & _MaxFmt & "</text>" &
			    "<text x='" & (_PadL-4) & "' y='" & (_PadT+_PlotH) & "' text-anchor='end' font-size='8' fill='#bbb'>" & _MinFmt & "</text>" &
			
			    -- Area fill under 2024 line
			    "<polygon points='" & _AreaPts & "' fill='#1A5C5A' fill-opacity='0.07'/>" &
			
			    -- 2023 dashed line
			    "<polyline points='" & _Pts23 & "' fill='none' stroke='#C8C4BC' stroke-width='1.5' stroke-dasharray='4 3'/>" &
			
			    -- 2024 solid line
			    "<polyline points='" & _Pts24 & "' fill='none' stroke='#1A5C5A' stroke-width='2'/>" &
			
			    -- December 2024 endpoint dot
			    "<circle cx='" & FORMAT(_DotX,"0") & "' cy='" & FORMAT(_DotY,"0.0") & "' r='4' fill='#1A5C5A'/>" &
			
			    -- Month labels
			    _MonthLbls &
			
			  "</svg>" &
			
			  -- Legend
			  "<div style='display:flex;gap:16px;margin-top:5px'>" &
			    "<div style='display:flex;align-items:center;gap:5px;font-size:9px;color:#555'>" &
			      "<svg width='18' height='8'><line x1='0' y1='4' x2='18' y2='4' stroke='#1A5C5A' stroke-width='2'/></svg>" &
			      "2024 (current)</div>" &
			    "<div style='display:flex;align-items:center;gap:5px;font-size:9px;color:#999'>" &
			      "<svg width='18' height='8'><line x1='0' y1='4' x2='18' y2='4' stroke='#C8C4BC'" &
			      " stroke-width='1.5' stroke-dasharray=""4 2""/></svg>" &
			      "2023 (prior year)</div>" &
			  "</div>" &
			
			"</div>"
			```
		lineageTag: b9a07c75-835c-4dd0-b2f3-89c6a9b1d99f

	column Column1
		dataType: string
		lineageTag: 58a8cd9b-f39f-4372-8976-5f73eb4c75e3
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	partition _Measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

