table Dim_Target
	lineageTag: 8a6c2451-5122-4efa-9f54-c09d58a40331

	column Target_ID
		dataType: string
		lineageTag: 7164cec6-ff28-4df3-b427-259358d378fd
		summarizeBy: none
		sourceColumn: Target_ID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: c1574901-be1b-4eb3-94ec-45a50d77c0e8
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column Channel
		dataType: string
		lineageTag: 2ac1e3a0-7570-4ce9-9e34-81cb3bc9be32
		summarizeBy: none
		sourceColumn: Channel

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: 15e9f96f-bf85-4fe2-9ed3-3a3cc3edf061
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: string
		lineageTag: b92e6a71-cbe0-4617-a87e-33dcd81d6a14
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column Sales_Target
		dataType: double
		lineageTag: 0ee9a777-6fe4-4952-9927-6852257afb21
		summarizeBy: sum
		sourceColumn: Sales_Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Availability_Target
		dataType: double
		lineageTag: 7659f30b-0e79-43da-ba8a-7f1a085bf2e4
		summarizeBy: sum
		sourceColumn: Availability_Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FillRate_Target
		dataType: double
		lineageTag: 3cad6aad-284d-4a0a-b20e-77d8e19b237d
		summarizeBy: sum
		sourceColumn: FillRate_Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Dim_region.region_id'
		dataType: string
		lineageTag: cba7cd9d-aff5-43e2-bdbc-e73a29cd7b76
		summarizeBy: none
		sourceColumn: Dim_region.region_id

		annotation SummarizationSetBy = Automatic

	column 'Dim_channel.channel_id'
		dataType: string
		lineageTag: e321d890-65c7-4077-8e07-0b6dadeaaac3
		summarizeBy: none
		sourceColumn: Dim_channel.channel_id

		annotation SummarizationSetBy = Automatic

	partition Dim_Target = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\fmcg project\data\FMCG_2022_2024.xlsx"), null, true),
				    Dim_Target_Sheet = Source{[Item="Dim_Target",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dim_Target_Sheet, [PromoteAllScalars=true]),
				    #"Added Prefix" = Table.TransformColumns(#"Promoted Headers", {{"Region", each "PL-" & _, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Added Prefix", {"Region"}, Dim_region, {"region"}, "Dim_region", JoinKind.LeftOuter),
				    #"Replaced Value" = Table.ReplaceValue(#"Merged Queries","Wholesale","Discount",Replacer.ReplaceText,{"Channel"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Online","E-commerce",Replacer.ReplaceText,{"Channel"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Replaced Value1", {"Channel"}, Dim_channel, {"channel"}, "Dim_channel", JoinKind.LeftOuter),
				    #"Expanded Dim_region" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_region", {"region_id"}, {"Dim_region.region_id"}),
				    #"Expanded Dim_channel" = Table.ExpandTableColumn(#"Expanded Dim_region", "Dim_channel", {"channel_id"}, {"Dim_channel.channel_id"}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Dim_channel",{{"Sales_Target", type number}, {"Availability_Target", type number}, {"FillRate_Target", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

