table Dim_target
	lineageTag: bbe50862-cb29-4f08-af8a-40fbe5745c7b

	column target_id
		dataType: string
		lineageTag: 550a793e-b1a3-4d7f-bedc-a625e3865e12
		summarizeBy: none
		sourceColumn: target_id

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 4b583ba4-a482-4e99-9226-843a64573811
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column channel
		dataType: string
		lineageTag: e5954814-f790-48c9-a992-c596979bf833
		summarizeBy: none
		sourceColumn: channel

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		formatString: 0
		lineageTag: 48227229-e51b-4541-b652-4c93ec75df65
		summarizeBy: sum
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column month
		dataType: string
		lineageTag: e7a067ee-5849-4793-b308-42ebb7580204
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column sales_target
		dataType: int64
		formatString: 0
		lineageTag: 0c80a61b-cbc4-4a0f-9520-fd13ffb4ab36
		summarizeBy: sum
		sourceColumn: sales_target

		annotation SummarizationSetBy = Automatic

	column distribution_target_%
		dataType: int64
		formatString: 0
		lineageTag: ee28f866-d826-476a-8bf3-f90ad728e20b
		summarizeBy: sum
		sourceColumn: distribution_target_%

		annotation SummarizationSetBy = Automatic

	column outlet_coverage_target_%
		dataType: int64
		formatString: 0
		lineageTag: 1c115689-c107-4fda-b242-e822348c974a
		summarizeBy: sum
		sourceColumn: outlet_coverage_target_%

		annotation SummarizationSetBy = Automatic

	column Target_Key =
			
			Dim_Target[region]
			& "_"
			& Dim_Target[channel]
			& "_"
			& Dim_Target[year]
			& "_"
			& Dim_Target[month]
		lineageTag: 32c16dcc-7695-47ee-84d1-2e390a10c522
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Dim_region.region_id'
		dataType: string
		lineageTag: cace997f-c318-4fec-ab42-b1a31c8e948c
		summarizeBy: none
		sourceColumn: Dim_region.region_id

		annotation SummarizationSetBy = Automatic

	column 'Dim_channel.channel_id'
		dataType: string
		lineageTag: cc95df9f-0eed-4169-a9f2-5cd42a20b6fb
		summarizeBy: none
		sourceColumn: Dim_channel.channel_id

		annotation SummarizationSetBy = Automatic

	partition Dim_target = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\fmcg project\data\FMCG_2022_2024.xlsx"), null, true),
				    Dim_target_Sheet = Source{[Item="Dim_target",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Dim_target_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"target_id", type text}, {"region", type text}, {"channel", type text}, {"year", Int64.Type}, {"month", type text}, {"sales_target", Int64.Type}, {"distribution_target_%", Int64.Type}, {"outlet_coverage_target_%", Int64.Type}}),
				    #"Added Prefix" = Table.TransformColumns(#"Changed Type", {{"region", each "PL-" & _, type text}}),
				    #"Merged Queries" = Table.NestedJoin(#"Added Prefix", {"region"}, Dim_region, {"region"}, "Dim_region", JoinKind.LeftOuter),
				    #"Expanded Dim_region" = Table.ExpandTableColumn(#"Merged Queries", "Dim_region", {"region_id"}, {"Dim_region.region_id"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Expanded Dim_region","Online","E-commerce",Replacer.ReplaceText,{"channel"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Wholesale","Discount",Replacer.ReplaceText,{"channel"}),
				    #"Merged Queries1" = Table.NestedJoin(#"Replaced Value1", {"channel"}, Dim_channel, {"channel"}, "Dim_channel", JoinKind.LeftOuter),
				    #"Expanded Dim_channel" = Table.ExpandTableColumn(#"Merged Queries1", "Dim_channel", {"channel_id"}, {"Dim_channel.channel_id"})
				in
				    #"Expanded Dim_channel"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

