table Dim_Product
	lineageTag: a8f58b4f-0ff1-4406-ab4a-4fcaaa3dcfa3

	column Product_id
		dataType: string
		lineageTag: f58ed22e-55f1-45b4-a2b4-c6a900f66291
		summarizeBy: none
		sourceColumn: Product_id

		annotation SummarizationSetBy = Automatic

	column sku
		dataType: string
		lineageTag: 5f073c43-ee1c-40f7-8120-f774d368580a
		summarizeBy: none
		sourceColumn: sku

		annotation SummarizationSetBy = Automatic

	column brand
		dataType: string
		lineageTag: c6b3ebd3-437a-4b4f-a0d3-0093f238cdb1
		summarizeBy: none
		sourceColumn: brand

		annotation SummarizationSetBy = Automatic

	column segment
		dataType: string
		lineageTag: c7534516-a246-413c-95f3-ca887a92567b
		summarizeBy: none
		sourceColumn: segment

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 04f07cc1-5cb7-411b-a59c-4b8ce5ea1f89
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column pack_type
		dataType: string
		lineageTag: be854cde-bf99-4ead-8c7b-4ae08ae6bdd7
		summarizeBy: none
		sourceColumn: pack_type

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\fmcg project\data\FMCG_2022_2024.xlsx"), null, true),
				    Dim_Product_Sheet = Source{[Item="Dim_Product",Kind="Sheet"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Product_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "product_id"}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Renamed Columns", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product_id", type text}, {"sku", type text}, {"brand", type text}, {"segment", type text}, {"category", type text}, {"pack_type", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

